spring:
  profiles:
    active: local
  jpa:
  generate-ddl: false
  #    show-sql: true
  hibernate:
    use-new-id-generator-mappings: false
  database-platform: org.hibernate.dialect.PostgreSQLDialect

  cors:
    allowedOrigins: ${CORS_ALLOWED_ORIGINS:https://localhost:8081, https://localhost:8082, https://localhost:3000, https://cntr.oilpc.local}
