server:
  ip: localhost
  port: 8080
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/one-to-one/api}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/one_to_one
    username: ${DB_USERNAME:one_to_one}
    password: ${DB_PASSWORD:onetoone}

  mail:
    host: smtp.yandex.ru
    username: ${emailSenderLogin.local}
    password: ${emailSenderPassword.local}
    port: 465
    protocol: smtp
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.ssl.enable": true
      "mail.smtp.ssl.protocols": TLSv1.2
  cors:
    allowedOrigins: ${CORS_ALLOWED_ORIGINS:*}

  security:
    ignored=/**:
    basic:
      enabled: false
    management:
      security: false
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    generate-ddl: false
    #    show-sql: true

jwt:
  secret:
    access: g54ges5tW$%tw45TEgsegrfdrfer
    refresh: 5w4gew5g4G$G4gsasgfDGSDG6regS
  expiration:
    access: 10
    refresh: 30

springdoc:
  swagger-ui:
    enabled: true
  swagger-ui.path: /swagger-ui.html


