CREATE SEQUENCE technologies_id_seq
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

CREATE TABLE technologies
(
    id   BIGINT      NOT NULL DEFAULT nextval('technologies_id_seq'::regclass),
    name VARCHAR(64) NOT NULL UNIQUE,
    CONSTRAINT technologies_pkey PRIMARY KEY (id),
    CONSTRAINT uq_name UNIQUE (name)
);

INSERT INTO technologies
VALUES (nextval('technologies_id_seq'::regclass), 'JavaScript'),
       (nextval('technologies_id_seq'::regclass), '.NET Core'),
       (nextval('technologies_id_seq'::regclass), 'Amazon DynamoDB'),
       (nextval('technologies_id_seq'::regclass), 'Amazon Echo/Alexa'),
       (nextval('technologies_id_seq'::regclass), 'Amazon RDS'),
       (nextval('technologies_id_seq'::regclass), 'Amazon Redshift'),
       (nextval('technologies_id_seq'::regclass), 'Android'),
       (nextval('technologies_id_seq'::regclass), 'Angular'),
       (nextval('technologies_id_seq'::regclass), 'Apache HBase'),
       (nextval('technologies_id_seq'::regclass), 'Apache Hive'),
       (nextval('technologies_id_seq'::regclass), 'Apache Spark'),
       (nextval('technologies_id_seq'::regclass), 'Apple TV'),
       (nextval('technologies_id_seq'::regclass), 'Apple Watch'),
       (nextval('technologies_id_seq'::regclass), 'Arduino'),
       (nextval('technologies_id_seq'::regclass), 'Assembly'),
       (nextval('technologies_id_seq'::regclass), 'AWS'),
       (nextval('technologies_id_seq'::regclass), 'Bash/Shell'),
       (nextval('technologies_id_seq'::regclass), 'C'),
       (nextval('technologies_id_seq'::regclass), 'C#'),
       (nextval('technologies_id_seq'::regclass), 'C++'),
       (nextval('technologies_id_seq'::regclass), 'Cassandra'),
       (nextval('technologies_id_seq'::regclass), 'Clojure'),
       (nextval('technologies_id_seq'::regclass), 'COBOL'),
       (nextval('technologies_id_seq'::regclass), 'CoffeeScript'),
       (nextval('technologies_id_seq'::regclass), 'Cordova'),
       (nextval('technologies_id_seq'::regclass), 'CSS'),
       (nextval('technologies_id_seq'::regclass), 'Delphi/Object Pascal'),
       (nextval('technologies_id_seq'::regclass), 'Django'),
       (nextval('technologies_id_seq'::regclass), 'Drupal'),
       (nextval('technologies_id_seq'::regclass), 'Elasticsearch'),
       (nextval('technologies_id_seq'::regclass), 'Erlang'),
       (nextval('technologies_id_seq'::regclass), 'ESP8266'),
       (nextval('technologies_id_seq'::regclass), 'F#'),
       (nextval('technologies_id_seq'::regclass), 'Firebase'),
       (nextval('technologies_id_seq'::regclass), 'Gaming console'),
       (nextval('technologies_id_seq'::regclass), 'Go'),
       (nextval('technologies_id_seq'::regclass), 'Google App Engine'),
       (nextval('technologies_id_seq'::regclass), 'Google BigQuery'),
       (nextval('technologies_id_seq'::regclass), 'Google Cloud Platform'),
       (nextval('technologies_id_seq'::regclass), 'Google Cloud Storage'),
       (nextval('technologies_id_seq'::regclass), 'Google Home'),
       (nextval('technologies_id_seq'::regclass), 'Groovy'),
       (nextval('technologies_id_seq'::regclass), 'Hack'),
       (nextval('technologies_id_seq'::regclass), 'Hadoop'),
       (nextval('technologies_id_seq'::regclass), 'Haskell'),
       (nextval('technologies_id_seq'::regclass), 'Heroku'),
       (nextval('technologies_id_seq'::regclass), 'HTML'),
       (nextval('technologies_id_seq'::regclass), 'IBM Cloud'),
       (nextval('technologies_id_seq'::regclass), 'IBM Db2'),
       (nextval('technologies_id_seq'::regclass), 'IBM Watson'),
       (nextval('technologies_id_seq'::regclass), 'iOS'),
       (nextval('technologies_id_seq'::regclass), 'Java'),
       (nextval('technologies_id_seq'::regclass), 'Julia'),
       (nextval('technologies_id_seq'::regclass), 'Kotlin'),
       (nextval('technologies_id_seq'::regclass), 'Linux'),
       (nextval('technologies_id_seq'::regclass), 'Lua'),
       (nextval('technologies_id_seq'::regclass), 'Mac OS'),
       (nextval('technologies_id_seq'::regclass), 'Mainframe'),
       (nextval('technologies_id_seq'::regclass), 'MariaDB'),
       (nextval('technologies_id_seq'::regclass), 'MATLAB'),
       (nextval('technologies_id_seq'::regclass), 'Memcached'),
       (nextval('technologies_id_seq'::regclass), 'Microsoft Azure'),
       (nextval('technologies_id_seq'::regclass), 'MongoDB'),
       (nextval('technologies_id_seq'::regclass), 'MySQL'),
       (nextval('technologies_id_seq'::regclass), 'Neo4j'),
       (nextval('technologies_id_seq'::regclass), 'Node.js'),
       (nextval('technologies_id_seq'::regclass), 'Objective-C'),
       (nextval('technologies_id_seq'::regclass), 'OCaml'),
       (nextval('technologies_id_seq'::regclass), 'Oracle'),
       (nextval('technologies_id_seq'::regclass), 'Perl'),
       (nextval('technologies_id_seq'::regclass), 'PHP'),
       (nextval('technologies_id_seq'::regclass), 'PlayStation'),
       (nextval('technologies_id_seq'::regclass), 'PostgreSQL'),
       (nextval('technologies_id_seq'::regclass), 'Predix'),
       (nextval('technologies_id_seq'::regclass), 'Python'),
       (nextval('technologies_id_seq'::regclass), 'PyTorch'),
       (nextval('technologies_id_seq'::regclass), 'R'),
       (nextval('technologies_id_seq'::regclass), 'Raspberry Pi'),
       (nextval('technologies_id_seq'::regclass), 'React'),
       (nextval('technologies_id_seq'::regclass), 'Redis'),
       (nextval('technologies_id_seq'::regclass), 'Ruby'),
       (nextval('technologies_id_seq'::regclass), 'Rust'),
       (nextval('technologies_id_seq'::regclass), 'Salesforce'),
       (nextval('technologies_id_seq'::regclass), 'Scala'),
       (nextval('technologies_id_seq'::regclass), 'Serverless'),
       (nextval('technologies_id_seq'::regclass), 'SharePoint'),
       (nextval('technologies_id_seq'::regclass), 'Spring'),
       (nextval('technologies_id_seq'::regclass), 'SQL'),
       (nextval('technologies_id_seq'::regclass), 'SQL Server'),
       (nextval('technologies_id_seq'::regclass), 'SQLite'),
       (nextval('technologies_id_seq'::regclass), 'Swift'),
       (nextval('technologies_id_seq'::regclass), 'TensorFlow'),
       (nextval('technologies_id_seq'::regclass), 'Torch'),
       (nextval('technologies_id_seq'::regclass), 'TypeScript'),
       (nextval('technologies_id_seq'::regclass), 'VB.NET'),
       (nextval('technologies_id_seq'::regclass), 'VBA'),
       (nextval('technologies_id_seq'::regclass), 'Visual Basic'),
       (nextval('technologies_id_seq'::regclass), 'Windows Desktop'),
       (nextval('technologies_id_seq'::regclass), 'Windows Phone'),
       (nextval('technologies_id_seq'::regclass), 'Windows Server'),
       (nextval('technologies_id_seq'::regclass), 'WordPress'),
       (nextval('technologies_id_seq'::regclass), 'Xamarin'),
       (nextval('technologies_id_seq'::regclass), 'Xbox'),
       (nextval('technologies_id_seq'::regclass), '.NET'),
       (nextval('technologies_id_seq'::regclass), 'ABAP'),
       (nextval('technologies_id_seq'::regclass), 'Ada'),
       (nextval('technologies_id_seq'::regclass), 'Ajax'),
       (nextval('technologies_id_seq'::regclass), 'Amazon Web Services'),
       (nextval('technologies_id_seq'::regclass), 'Amp'),
       (nextval('technologies_id_seq'::regclass), 'Ansible'),
       (nextval('technologies_id_seq'::regclass), 'ASP.NET'),
       (nextval('technologies_id_seq'::regclass), 'Assembly language'),
       (nextval('technologies_id_seq'::regclass), 'Babel'),
       (nextval('technologies_id_seq'::regclass), 'Bash'),
       (nextval('technologies_id_seq'::regclass), 'Bitcoin'),
       (nextval('technologies_id_seq'::regclass), 'Blockchain'),
       (nextval('technologies_id_seq'::regclass), 'Bootstrap'),
       (nextval('technologies_id_seq'::regclass), 'Chrome extension'),
       (nextval('technologies_id_seq'::regclass), 'Cryptocurrency'),
       (nextval('technologies_id_seq'::regclass), 'Crystal'),
       (nextval('technologies_id_seq'::regclass), 'D'),
       (nextval('technologies_id_seq'::regclass), 'Dart'),
       (nextval('technologies_id_seq'::regclass), 'Docker'),
       (nextval('technologies_id_seq'::regclass), 'Electron'),
       (nextval('technologies_id_seq'::regclass), 'Elixir'),
       (nextval('technologies_id_seq'::regclass), 'Ember.js'),
       (nextval('technologies_id_seq'::regclass), 'ES6'),
       (nextval('technologies_id_seq'::regclass), 'Ethereum'),
       (nextval('technologies_id_seq'::regclass), 'Express'),
       (nextval('technologies_id_seq'::regclass), 'Firefox'),
       (nextval('technologies_id_seq'::regclass), 'Flask'),
       (nextval('technologies_id_seq'::regclass), 'Fortran'),
       (nextval('technologies_id_seq'::regclass), 'Git'),
       (nextval('technologies_id_seq'::regclass), 'Gradle'),
       (nextval('technologies_id_seq'::regclass), 'GraphQL'),
       (nextval('technologies_id_seq'::regclass), 'Grunt'),
       (nextval('technologies_id_seq'::regclass), 'Gulp'),
       (nextval('technologies_id_seq'::regclass), 'Homebrew'),
       (nextval('technologies_id_seq'::regclass), 'Homebridge'),
       (nextval('technologies_id_seq'::regclass), 'IPFS'),
       (nextval('technologies_id_seq'::regclass), 'Jekyll'),
       (nextval('technologies_id_seq'::regclass), 'jQuery'),
       (nextval('technologies_id_seq'::regclass), 'JSON'),
       (nextval('technologies_id_seq'::regclass), 'Jupyter'),
       (nextval('technologies_id_seq'::regclass), 'Koa'),
       (nextval('technologies_id_seq'::regclass), 'Kubernetes'),
       (nextval('technologies_id_seq'::regclass), 'LabVIEW'),
       (nextval('technologies_id_seq'::regclass), 'Ladder Logic'),
       (nextval('technologies_id_seq'::regclass), 'Laravel'),
       (nextval('technologies_id_seq'::regclass), 'LaTeX'),
       (nextval('technologies_id_seq'::regclass), 'Lisp'),
       (nextval('technologies_id_seq'::regclass), 'Logo'),
       (nextval('technologies_id_seq'::regclass), 'macOS'),
       (nextval('technologies_id_seq'::regclass), 'Markdown'),
       (nextval('technologies_id_seq'::regclass), 'Mastodon'),
       (nextval('technologies_id_seq'::regclass), 'Material design'),
       (nextval('technologies_id_seq'::regclass), 'Maven'),
       (nextval('technologies_id_seq'::regclass), 'Minecraft'),
       (nextval('technologies_id_seq'::regclass), 'Monero'),
       (nextval('technologies_id_seq'::regclass), 'Mongoose'),
       (nextval('technologies_id_seq'::regclass), 'MvvmCross'),
       (nextval('technologies_id_seq'::regclass), 'NativeScript'),
       (nextval('technologies_id_seq'::regclass), 'Nim'),
       (nextval('technologies_id_seq'::regclass), 'NoSQL'),
       (nextval('technologies_id_seq'::regclass), 'OpenGL'),
       (nextval('technologies_id_seq'::regclass), 'Perl 6'),
       (nextval('technologies_id_seq'::regclass), 'Phaser'),
       (nextval('technologies_id_seq'::regclass), 'PICO-8'),
       (nextval('technologies_id_seq'::regclass), 'PL/I'),
       (nextval('technologies_id_seq'::regclass), 'PL/SQL'),
       (nextval('technologies_id_seq'::regclass), 'PostScript'),
       (nextval('technologies_id_seq'::regclass), 'Prolog'),
       (nextval('technologies_id_seq'::regclass), 'PWA'),
       (nextval('technologies_id_seq'::regclass), 'Qt'),
       (nextval('technologies_id_seq'::regclass), 'Rails'),
       (nextval('technologies_id_seq'::regclass), 'Ratchet'),
       (nextval('technologies_id_seq'::regclass), 'React Native'),
       (nextval('technologies_id_seq'::regclass), 'ReactiveUI'),
       (nextval('technologies_id_seq'::regclass), 'Redux'),
       (nextval('technologies_id_seq'::regclass), 'REST API'),
       (nextval('technologies_id_seq'::regclass), 'RPG'),
       (nextval('technologies_id_seq'::regclass), 'SAS'),
       (nextval('technologies_id_seq'::regclass), 'Sass'),
       (nextval('technologies_id_seq'::regclass), 'Scheme'),
       (nextval('technologies_id_seq'::regclass), 'scikit-learn'),
       (nextval('technologies_id_seq'::regclass), 'Scratch'),
       (nextval('technologies_id_seq'::regclass), 'Shell'),
       (nextval('technologies_id_seq'::regclass), 'Sketch'),
       (nextval('technologies_id_seq'::regclass), 'Spring Boot'),
       (nextval('technologies_id_seq'::regclass), 'Standard ML'),
       (nextval('technologies_id_seq'::regclass), 'Storybook'),
       (nextval('technologies_id_seq'::regclass), 'Symfony'),
       (nextval('technologies_id_seq'::regclass), 'Tcl'),
       (nextval('technologies_id_seq'::regclass), 'Telegram'),
       (nextval('technologies_id_seq'::regclass), 'Terminal'),
       (nextval('technologies_id_seq'::regclass), 'Terraform'),
       (nextval('technologies_id_seq'::regclass), 'Transact-SQL'),
       (nextval('technologies_id_seq'::regclass), 'Ubuntu'),
       (nextval('technologies_id_seq'::regclass), 'Unity'),
       (nextval('technologies_id_seq'::regclass), 'Unreal Engine'),
       (nextval('technologies_id_seq'::regclass), 'Vagrant'),
       (nextval('technologies_id_seq'::regclass), 'Vim'),
       (nextval('technologies_id_seq'::regclass), 'Visual Basic .NET'),
       (nextval('technologies_id_seq'::regclass), 'Vue.js'),
       (nextval('technologies_id_seq'::regclass), 'Wagtail'),
       (nextval('technologies_id_seq'::regclass), 'Web Components'),
       (nextval('technologies_id_seq'::regclass), 'Webpack'),
       (nextval('technologies_id_seq'::regclass), 'Windows'),
       (nextval('technologies_id_seq'::regclass), 'WordPlate'),
       (nextval('technologies_id_seq'::regclass), 'XML'),
       (nextval('technologies_id_seq'::regclass), 'YAML'),
       (nextval('technologies_id_seq'::regclass), 'Akka'),
       (nextval('technologies_id_seq'::regclass), 'Amazon Elastic Compute Cloud'),
       (nextval('technologies_id_seq'::regclass), 'AngularJS'),
       (nextval('technologies_id_seq'::regclass), 'AnyChart'),
       (nextval('technologies_id_seq'::regclass), 'AOLserver'),
       (nextval('technologies_id_seq'::regclass), 'Apache'),
       (nextval('technologies_id_seq'::regclass), 'Apache Cassandra'),
       (nextval('technologies_id_seq'::regclass), 'Apache Kafka'),
       (nextval('technologies_id_seq'::regclass), 'Apache Mesos'),
       (nextval('technologies_id_seq'::regclass), 'AppScale'),
       (nextval('technologies_id_seq'::regclass), 'Backbone.js'),
       (nextval('technologies_id_seq'::regclass), 'BaseX'),
       (nextval('technologies_id_seq'::regclass), 'Bass CSS'),
       (nextval('technologies_id_seq'::regclass), 'Bulma'),
       (nextval('technologies_id_seq'::regclass), 'Cannon.js'),
       (nextval('technologies_id_seq'::regclass), 'Cappuccino'),
       (nextval('technologies_id_seq'::regclass), 'Cascade Framework'),
       (nextval('technologies_id_seq'::regclass), 'Cassowary'),
       (nextval('technologies_id_seq'::regclass), 'Chaplin.js'),
       (nextval('technologies_id_seq'::regclass), 'CHR.js'),
       (nextval('technologies_id_seq'::regclass), 'CouchDB'),
       (nextval('technologies_id_seq'::regclass), 'D3.js'),
       (nextval('technologies_id_seq'::regclass), 'Dojo Toolkit'),
       (nextval('technologies_id_seq'::regclass), 'Dojo Widgets'),
       (nextval('technologies_id_seq'::regclass), 'DRBD (Distributed Replicated Block Device)'),
       (nextval('technologies_id_seq'::regclass), 'Echo'),
       (nextval('technologies_id_seq'::regclass), 'Enyo'),
       (nextval('technologies_id_seq'::regclass), 'Eucalyptus'),
       (nextval('technologies_id_seq'::regclass), 'eXist'),
       (nextval('technologies_id_seq'::regclass), 'Ext JS'),
       (nextval('technologies_id_seq'::regclass), 'Foundation'),
       (nextval('technologies_id_seq'::regclass), 'FusionCharts'),
       (nextval('technologies_id_seq'::regclass), 'Ganeti'),
       (nextval('technologies_id_seq'::regclass), 'Ganeti Web Manager'),
       (nextval('technologies_id_seq'::regclass), 'GemStone'),
       (nextval('technologies_id_seq'::regclass), 'Glow'),
       (nextval('technologies_id_seq'::regclass), 'Google Closure Library'),
       (nextval('technologies_id_seq'::regclass), 'Google Polymer'),
       (nextval('technologies_id_seq'::regclass), 'Google Web Toolkit'),
       (nextval('technologies_id_seq'::regclass), 'Highcharts'),
       (nextval('technologies_id_seq'::regclass), 'httpd'),
       (nextval('technologies_id_seq'::regclass), 'Hypervisor'),
       (nextval('technologies_id_seq'::regclass), 'Internet Information Services'),
       (nextval('technologies_id_seq'::regclass), 'Jasmine'),
       (nextval('technologies_id_seq'::regclass), 'JavaScript InfoVis Toolkit'),
       (nextval('technologies_id_seq'::regclass), 'JavaScriptMVC'),
       (nextval('technologies_id_seq'::regclass), 'Jinja-JS'),
       (nextval('technologies_id_seq'::regclass), 'Joose'),
       (nextval('technologies_id_seq'::regclass), 'jQuery Mobile'),
       (nextval('technologies_id_seq'::regclass), 'jQuery UI'),
       (nextval('technologies_id_seq'::regclass), 'jQWidgets'),
       (nextval('technologies_id_seq'::regclass), 'JsPHP'),
       (nextval('technologies_id_seq'::regclass), 'JsRender/JsViews'),
       (nextval('technologies_id_seq'::regclass), 'Kibana'),
       (nextval('technologies_id_seq'::regclass), 'Knockout'),
       (nextval('technologies_id_seq'::regclass), 'KVM'),
       (nextval('technologies_id_seq'::regclass), 'Lighttpd'),
       (nextval('technologies_id_seq'::regclass), 'Lively Kernel'),
       (nextval('technologies_id_seq'::regclass), 'Logstash'),
       (nextval('technologies_id_seq'::regclass), 'LVM'),
       (nextval('technologies_id_seq'::regclass), 'MarkLogic Server'),
       (nextval('technologies_id_seq'::regclass), 'Markup'),
       (nextval('technologies_id_seq'::regclass), 'Materialize'),
       (nextval('technologies_id_seq'::regclass), 'MathJax'),
       (nextval('technologies_id_seq'::regclass), 'Meteor'),
       (nextval('technologies_id_seq'::regclass), 'Microsofs Ajax library'),
       (nextval('technologies_id_seq'::regclass), 'midori'),
       (nextval('technologies_id_seq'::regclass), 'Miligram'),
       (nextval('technologies_id_seq'::regclass), 'Mnesia'),
       (nextval('technologies_id_seq'::regclass), 'Mocha'),
       (nextval('technologies_id_seq'::regclass), 'MochiKit'),
       (nextval('technologies_id_seq'::regclass), 'Modernizr'),
       (nextval('technologies_id_seq'::regclass), 'Mojito'),
       (nextval('technologies_id_seq'::regclass), 'MooTools'),
       (nextval('technologies_id_seq'::regclass), 'Mustache'),
       (nextval('technologies_id_seq'::regclass), 'Nginx'),
       (nextval('technologies_id_seq'::regclass), 'OpenACS'),
       (nextval('technologies_id_seq'::regclass), 'OpenBSD'),
       (nextval('technologies_id_seq'::regclass), 'OpenUI5'),
       (nextval('technologies_id_seq'::regclass), 'Oracle Database'),
       (nextval('technologies_id_seq'::regclass), 'p5.js'),
       (nextval('technologies_id_seq'::regclass), 'PDF.js'),
       (nextval('technologies_id_seq'::regclass), 'Pixi.js'),
       (nextval('technologies_id_seq'::regclass), 'Plotly'),
       (nextval('technologies_id_seq'::regclass), 'Polymer'),
       (nextval('technologies_id_seq'::regclass), 'Processing.js'),
       (nextval('technologies_id_seq'::regclass), 'Prototype JavaScript Framework'),
       (nextval('technologies_id_seq'::regclass), 'Pure CSS'),
       (nextval('technologies_id_seq'::regclass), 'PureMVC'),
       (nextval('technologies_id_seq'::regclass), 'qooxdoo'),
       (nextval('technologies_id_seq'::regclass), 'QUnit'),
       (nextval('technologies_id_seq'::regclass), 'Raphaël'),
       (nextval('technologies_id_seq'::regclass), 'REST'),
       (nextval('technologies_id_seq'::regclass), 'Riak'),
       (nextval('technologies_id_seq'::regclass), 'Rialto Toolkit'),
       (nextval('technologies_id_seq'::regclass), 'Rico'),
       (nextval('technologies_id_seq'::regclass), 'Script.aculo.us'),
       (nextval('technologies_id_seq'::regclass), 'Seaside'),
       (nextval('technologies_id_seq'::regclass), 'Semantic'),
       (nextval('technologies_id_seq'::regclass), 'Skeleton'),
       (nextval('technologies_id_seq'::regclass), 'Smalltalk'),
       (nextval('technologies_id_seq'::regclass), 'SmartClient'),
       (nextval('technologies_id_seq'::regclass), 'Socket.IO'),
       (nextval('technologies_id_seq'::regclass), 'Spectre'),
       (nextval('technologies_id_seq'::regclass), 'SproutCore'),
       (nextval('technologies_id_seq'::regclass), 'Spry framework'),
       (nextval('technologies_id_seq'::regclass), 'Susy'),
       (nextval('technologies_id_seq'::regclass), 'SWFObject'),
       (nextval('technologies_id_seq'::regclass), 'Tachyons'),
       (nextval('technologies_id_seq'::regclass), 'Teechart'),
       (nextval('technologies_id_seq'::regclass), 'Three.js'),
       (nextval('technologies_id_seq'::regclass), 'Topcoat'),
       (nextval('technologies_id_seq'::regclass), 'Total.js'),
       (nextval('technologies_id_seq'::regclass), 'Twig.js'),
       (nextval('technologies_id_seq'::regclass), 'Uikit'),
       (nextval('technologies_id_seq'::regclass), 'Underscore.js'),
       (nextval('technologies_id_seq'::regclass), 'Unit.js'),
       (nextval('technologies_id_seq'::regclass), 'Velocity.js'),
       (nextval('technologies_id_seq'::regclass), 'Verge3D'),
       (nextval('technologies_id_seq'::regclass), 'Wakanda Framework'),
       (nextval('technologies_id_seq'::regclass), 'Webix'),
       (nextval('technologies_id_seq'::regclass), 'WhitestormJS'),
       (nextval('technologies_id_seq'::regclass), 'WinJS'),
       (nextval('technologies_id_seq'::regclass), 'Xen'),
       (nextval('technologies_id_seq'::regclass), 'XForms'),
       (nextval('technologies_id_seq'::regclass), 'XQuery'),
       (nextval('technologies_id_seq'::regclass), 'Yaws'),
       (nextval('technologies_id_seq'::regclass), 'YUI Library'),
       (nextval('technologies_id_seq'::regclass), '(Visual) FoxPro'),
       (nextval('technologies_id_seq'::regclass), '4th Dimension/4D'),
       (nextval('technologies_id_seq'::regclass), 'ABC'),
       (nextval('technologies_id_seq'::regclass), 'ActionScript'),
       (nextval('technologies_id_seq'::regclass), 'Agilent VEE'),
       (nextval('technologies_id_seq'::regclass), 'ALGOL'),
       (nextval('technologies_id_seq'::regclass), 'Alice'),
       (nextval('technologies_id_seq'::regclass), 'AngelScript'),
       (nextval('technologies_id_seq'::regclass), 'Apex'),
       (nextval('technologies_id_seq'::regclass), 'APL'),
       (nextval('technologies_id_seq'::regclass), 'AppleScript'),
       (nextval('technologies_id_seq'::regclass), 'Arc'),
       (nextval('technologies_id_seq'::regclass), 'AspectJ'),
       (nextval('technologies_id_seq'::regclass), 'ATLAS'),
       (nextval('technologies_id_seq'::regclass), 'AutoIt'),
       (nextval('technologies_id_seq'::regclass), 'AutoLISP'),
       (nextval('technologies_id_seq'::regclass), 'Automator'),
       (nextval('technologies_id_seq'::regclass), 'Avenue'),
       (nextval('technologies_id_seq'::regclass), 'AWK'),
       (nextval('technologies_id_seq'::regclass), 'BASIC'),
       (nextval('technologies_id_seq'::regclass), 'BBC BASIC'),
       (nextval('technologies_id_seq'::regclass), 'bc'),
       (nextval('technologies_id_seq'::regclass), 'BCPL'),
       (nextval('technologies_id_seq'::regclass), 'BETA'),
       (nextval('technologies_id_seq'::regclass), 'BlitzMax'),
       (nextval('technologies_id_seq'::regclass), 'Boo'),
       (nextval('technologies_id_seq'::regclass), 'Bourne shell'),
       (nextval('technologies_id_seq'::regclass), 'C shell'),
       (nextval('technologies_id_seq'::regclass), 'C-Omega'),
       (nextval('technologies_id_seq'::regclass), 'Caml'),
       (nextval('technologies_id_seq'::regclass), 'Ceylon'),
       (nextval('technologies_id_seq'::regclass), 'CFML'),
       (nextval('technologies_id_seq'::regclass), 'Cg'),
       (nextval('technologies_id_seq'::regclass), 'Ch'),
       (nextval('technologies_id_seq'::regclass), 'Chapel'),
       (nextval('technologies_id_seq'::regclass), 'CHILL'),
       (nextval('technologies_id_seq'::regclass), 'CIL'),
       (nextval('technologies_id_seq'::regclass), 'CL (OS/400)'),
       (nextval('technologies_id_seq'::regclass), 'Clarion'),
       (nextval('technologies_id_seq'::regclass), 'Clean'),
       (nextval('technologies_id_seq'::regclass), 'Clipper'),
       (nextval('technologies_id_seq'::regclass), 'CLU'),
       (nextval('technologies_id_seq'::regclass), 'Cobra'),
       (nextval('technologies_id_seq'::regclass), 'COMAL'),
       (nextval('technologies_id_seq'::regclass), 'Common Lisp'),
       (nextval('technologies_id_seq'::regclass), 'cT'),
       (nextval('technologies_id_seq'::regclass), 'Curl'),
       (nextval('technologies_id_seq'::regclass), 'DCL'),
       (nextval('technologies_id_seq'::regclass), 'DIBOL'),
       (nextval('technologies_id_seq'::regclass), 'Dylan'),
       (nextval('technologies_id_seq'::regclass), 'E'),
       (nextval('technologies_id_seq'::regclass), 'ECMAScript'),
       (nextval('technologies_id_seq'::regclass), 'EGL'),
       (nextval('technologies_id_seq'::regclass), 'Eiffel'),
       (nextval('technologies_id_seq'::regclass), 'Elm'),
       (nextval('technologies_id_seq'::regclass), 'Emacs Lisp'),
       (nextval('technologies_id_seq'::regclass), 'Etoys'),
       (nextval('technologies_id_seq'::regclass), 'Euphoria'),
       (nextval('technologies_id_seq'::regclass), 'EXEC'),
       (nextval('technologies_id_seq'::regclass), 'Factor'),
       (nextval('technologies_id_seq'::regclass), 'Falcon'),
       (nextval('technologies_id_seq'::regclass), 'Fantom'),
       (nextval('technologies_id_seq'::regclass), 'Felix'),
       (nextval('technologies_id_seq'::regclass), 'Forth'),
       (nextval('technologies_id_seq'::regclass), 'Fortress'),
       (nextval('technologies_id_seq'::regclass), 'Gambas'),
       (nextval('technologies_id_seq'::regclass), 'GLSL'),
       (nextval('technologies_id_seq'::regclass), 'GNU Octave'),
       (nextval('technologies_id_seq'::regclass), 'Gosu'),
       (nextval('technologies_id_seq'::regclass), 'Haxe'),
       (nextval('technologies_id_seq'::regclass), 'Heron'),
       (nextval('technologies_id_seq'::regclass), 'HPL'),
       (nextval('technologies_id_seq'::regclass), 'HyperTalk'),
       (nextval('technologies_id_seq'::regclass), 'Icon'),
       (nextval('technologies_id_seq'::regclass), 'IDL'),
       (nextval('technologies_id_seq'::regclass), 'Idris'),
       (nextval('technologies_id_seq'::regclass), 'Inform'),
       (nextval('technologies_id_seq'::regclass), 'Informix-4GL'),
       (nextval('technologies_id_seq'::regclass), 'INTERCAL'),
       (nextval('technologies_id_seq'::regclass), 'Io'),
       (nextval('technologies_id_seq'::regclass), 'Ioke'),
       (nextval('technologies_id_seq'::regclass), 'J'),
       (nextval('technologies_id_seq'::regclass), 'J#'),
       (nextval('technologies_id_seq'::regclass), 'JADE'),
       (nextval('technologies_id_seq'::regclass), 'JavaFX Script'),
       (nextval('technologies_id_seq'::regclass), 'JScript'),
       (nextval('technologies_id_seq'::regclass), 'JScript.NET'),
       (nextval('technologies_id_seq'::regclass), 'Korn shell'),
       (nextval('technologies_id_seq'::regclass), 'Lasso'),
       (nextval('technologies_id_seq'::regclass), 'Limbo'),
       (nextval('technologies_id_seq'::regclass), 'Lingo'),
       (nextval('technologies_id_seq'::regclass), 'LiveCode'),
       (nextval('technologies_id_seq'::regclass), 'LotusScript'),
       (nextval('technologies_id_seq'::regclass), 'LPC'),
       (nextval('technologies_id_seq'::regclass), 'Lustre'),
       (nextval('technologies_id_seq'::regclass), 'm4'),
       (nextval('technologies_id_seq'::regclass), 'MAD'),
       (nextval('technologies_id_seq'::regclass), 'Magic'),
       (nextval('technologies_id_seq'::regclass), 'Magik'),
       (nextval('technologies_id_seq'::regclass), 'Malbolge'),
       (nextval('technologies_id_seq'::regclass), 'MANTIS'),
       (nextval('technologies_id_seq'::regclass), 'Maple'),
       (nextval('technologies_id_seq'::regclass), 'Max/MSP'),
       (nextval('technologies_id_seq'::regclass), 'MAXScript'),
       (nextval('technologies_id_seq'::regclass), 'MDX'),
       (nextval('technologies_id_seq'::regclass), 'MEL'),
       (nextval('technologies_id_seq'::regclass), 'Mercury'),
       (nextval('technologies_id_seq'::regclass), 'Miva'),
       (nextval('technologies_id_seq'::regclass), 'ML'),
       (nextval('technologies_id_seq'::regclass), 'Modula-2'),
       (nextval('technologies_id_seq'::regclass), 'Modula-3'),
       (nextval('technologies_id_seq'::regclass), 'Monkey'),
       (nextval('technologies_id_seq'::regclass), 'MOO'),
       (nextval('technologies_id_seq'::regclass), 'Moto'),
       (nextval('technologies_id_seq'::regclass), 'MQL4'),
       (nextval('technologies_id_seq'::regclass), 'MS-DOS batch'),
       (nextval('technologies_id_seq'::regclass), 'MUMPS'),
       (nextval('technologies_id_seq'::regclass), 'NATURAL'),
       (nextval('technologies_id_seq'::regclass), 'Nemerle'),
       (nextval('technologies_id_seq'::regclass), 'NetLogo'),
       (nextval('technologies_id_seq'::regclass), 'NQC'),
       (nextval('technologies_id_seq'::regclass), 'NSIS'),
       (nextval('technologies_id_seq'::regclass), 'NXT-G'),
       (nextval('technologies_id_seq'::regclass), 'Oberon'),
       (nextval('technologies_id_seq'::regclass), 'Object Rexx'),
       (nextval('technologies_id_seq'::regclass), 'occam'),
       (nextval('technologies_id_seq'::regclass), 'OpenCL'),
       (nextval('technologies_id_seq'::regclass), 'OpenEdge ABL'),
       (nextval('technologies_id_seq'::regclass), 'OPL'),
       (nextval('technologies_id_seq'::regclass), 'Oxygene'),
       (nextval('technologies_id_seq'::regclass), 'Oz'),
       (nextval('technologies_id_seq'::regclass), 'Paradox'),
       (nextval('technologies_id_seq'::regclass), 'Pascal'),
       (nextval('technologies_id_seq'::regclass), 'Pike'),
       (nextval('technologies_id_seq'::regclass), 'PILOT'),
       (nextval('technologies_id_seq'::regclass), 'Pliant'),
       (nextval('technologies_id_seq'::regclass), 'Pony'),
       (nextval('technologies_id_seq'::regclass), 'POV-Ray'),
       (nextval('technologies_id_seq'::regclass), 'PowerBASIC'),
       (nextval('technologies_id_seq'::regclass), 'PowerScript'),
       (nextval('technologies_id_seq'::regclass), 'PowerShell'),
       (nextval('technologies_id_seq'::regclass), 'Processing'),
       (nextval('technologies_id_seq'::regclass), 'Programming Without Coding Technology'),
       (nextval('technologies_id_seq'::regclass), 'Pure Data'),
       (nextval('technologies_id_seq'::regclass), 'PureBasic'),
       (nextval('technologies_id_seq'::regclass), 'Q'),
       (nextval('technologies_id_seq'::regclass), 'Racket'),
       (nextval('technologies_id_seq'::regclass), 'REBOL'),
       (nextval('technologies_id_seq'::regclass), 'Red'),
       (nextval('technologies_id_seq'::regclass), 'REXX'),
       (nextval('technologies_id_seq'::regclass), 'Ring'),
       (nextval('technologies_id_seq'::regclass), 'S'),
       (nextval('technologies_id_seq'::regclass), 'S-PLUS'),
       (nextval('technologies_id_seq'::regclass), 'Sather'),
       (nextval('technologies_id_seq'::regclass), 'sed'),
       (nextval('technologies_id_seq'::regclass), 'Seed7'),
       (nextval('technologies_id_seq'::regclass), 'SIGNAL'),
       (nextval('technologies_id_seq'::regclass), 'Simula'),
       (nextval('technologies_id_seq'::regclass), 'Simulink'),
       (nextval('technologies_id_seq'::regclass), 'Slate'),
       (nextval('technologies_id_seq'::regclass), 'Smarty'),
       (nextval('technologies_id_seq'::regclass), 'Snap!'),
       (nextval('technologies_id_seq'::regclass), 'Solidity'),
       (nextval('technologies_id_seq'::regclass), 'SPARK'),
       (nextval('technologies_id_seq'::regclass), 'SPSS'),
       (nextval('technologies_id_seq'::regclass), 'SQR'),
       (nextval('technologies_id_seq'::regclass), 'Squeak'),
       (nextval('technologies_id_seq'::regclass), 'Squirrel'),
       (nextval('technologies_id_seq'::regclass), 'Stata'),
       (nextval('technologies_id_seq'::regclass), 'Suneido'),
       (nextval('technologies_id_seq'::regclass), 'SuperCollider'),
       (nextval('technologies_id_seq'::regclass), 'TACL'),
       (nextval('technologies_id_seq'::regclass), 'tcsh'),
       (nextval('technologies_id_seq'::regclass), 'TeX'),
       (nextval('technologies_id_seq'::regclass), 'thinBasic'),
       (nextval('technologies_id_seq'::regclass), 'TOM'),
       (nextval('technologies_id_seq'::regclass), 'Vala/Genie'),
       (nextval('technologies_id_seq'::regclass), 'VBScript'),
       (nextval('technologies_id_seq'::regclass), 'Verilog'),
       (nextval('technologies_id_seq'::regclass), 'VHDL'),
       (nextval('technologies_id_seq'::regclass), 'WebAssembly'),
       (nextval('technologies_id_seq'::regclass), 'WebDNA'),
       (nextval('technologies_id_seq'::regclass), 'Whitespace'),
       (nextval('technologies_id_seq'::regclass), 'Wolfram'),
       (nextval('technologies_id_seq'::regclass), 'X10'),
       (nextval('technologies_id_seq'::regclass), 'xBase'),
       (nextval('technologies_id_seq'::regclass), 'XBase++'),
       (nextval('technologies_id_seq'::regclass), 'Xojo'),
       (nextval('technologies_id_seq'::regclass), 'XPL'),
       (nextval('technologies_id_seq'::regclass), 'XSLT'),
       (nextval('technologies_id_seq'::regclass), 'Xtend'),
       (nextval('technologies_id_seq'::regclass), 'yacc'),
       (nextval('technologies_id_seq'::regclass), 'Yorick'),
       (nextval('technologies_id_seq'::regclass), 'Z shell'),
       (nextval('technologies_id_seq'::regclass), '.NET Framework'),
       (nextval('technologies_id_seq'::regclass), '16-bit x86'),
       (nextval('technologies_id_seq'::regclass), '4D'),
       (nextval('technologies_id_seq'::regclass), '4D QL'),
       (nextval('technologies_id_seq'::regclass), '4DOS'),
       (nextval('technologies_id_seq'::regclass), '4th Dimension'),
       (nextval('technologies_id_seq'::regclass), '6502'),
       (nextval('technologies_id_seq'::regclass), '6510'),
       (nextval('technologies_id_seq'::regclass), '96Boards'),
       (nextval('technologies_id_seq'::regclass), 'A+'),
       (nextval('technologies_id_seq'::regclass), 'A-0 System'),
       (nextval('technologies_id_seq'::regclass), 'A-Frame'),
       (nextval('technologies_id_seq'::regclass), 'Ab Initio'),
       (nextval('technologies_id_seq'::regclass), 'ABAP Objects'),
       (nextval('technologies_id_seq'::regclass), 'ABCL/1'),
       (nextval('technologies_id_seq'::regclass), 'ABCL/c plus'),
       (nextval('technologies_id_seq'::regclass), 'ABCL/c+'),
       (nextval('technologies_id_seq'::regclass), 'ABCL/R'),
       (nextval('technologies_id_seq'::regclass), 'ABCL/R2'),
       (nextval('technologies_id_seq'::regclass), 'ABL'),
       (nextval('technologies_id_seq'::regclass), 'Accelerator'),
       (nextval('technologies_id_seq'::regclass), 'Accell/SQL'),
       (nextval('technologies_id_seq'::regclass), 'ActionScript 3.0'),
       (nextval('technologies_id_seq'::regclass), 'ActiveVFP'),
       (nextval('technologies_id_seq'::regclass), 'Actor'),
       (nextval('technologies_id_seq'::regclass), 'Ada 95'),
       (nextval('technologies_id_seq'::regclass), 'Adapteva'),
       (nextval('technologies_id_seq'::regclass), 'Adobe AIR'),
       (nextval('technologies_id_seq'::regclass), 'Adobe Flash‎'),
       (nextval('technologies_id_seq'::regclass), 'ADS/Online'),
       (nextval('technologies_id_seq'::regclass), 'Advanced Boolean Expression Language'),
       (nextval('technologies_id_seq'::regclass), 'Advanced Business Language'),
       (nextval('technologies_id_seq'::regclass), 'Agavi'),
       (nextval('technologies_id_seq'::regclass), 'Agda'),
       (nextval('technologies_id_seq'::regclass), 'Agora'),
       (nextval('technologies_id_seq'::regclass), 'AIDA/Web'),
       (nextval('technologies_id_seq'::regclass), 'Aiki Framework'),
       (nextval('technologies_id_seq'::regclass), 'AIMMS'),
       (nextval('technologies_id_seq'::regclass), 'Alchemy CMS'),
       (nextval('technologies_id_seq'::regclass), 'Aldor'),
       (nextval('technologies_id_seq'::regclass), 'Alef'),
       (nextval('technologies_id_seq'::regclass), 'ALF'),
       (nextval('technologies_id_seq'::regclass), 'Alfresco'),
       (nextval('technologies_id_seq'::regclass), 'ALGAE'),
       (nextval('technologies_id_seq'::regclass), 'ALGOL 58'),
       (nextval('technologies_id_seq'::regclass), 'ALGOL 60'),
       (nextval('technologies_id_seq'::regclass), 'ALGOL 68'),
       (nextval('technologies_id_seq'::regclass), 'ALGOL W'),
       (nextval('technologies_id_seq'::regclass), 'Allwinner Technology'),
       (nextval('technologies_id_seq'::regclass), 'Alma-0'),
       (nextval('technologies_id_seq'::regclass), 'Alphard'),
       (nextval('technologies_id_seq'::regclass), 'Altair BASIC'),
       (nextval('technologies_id_seq'::regclass), 'Altera Hardware Description Language'),
       (nextval('technologies_id_seq'::regclass), 'Amber'),
       (nextval('technologies_id_seq'::regclass), 'AMD'),
       (nextval('technologies_id_seq'::regclass), 'Ametys CMS'),
       (nextval('technologies_id_seq'::regclass), 'Amiga E'),
       (nextval('technologies_id_seq'::regclass), 'AMOS'),
       (nextval('technologies_id_seq'::regclass), 'AMPL'),
       (nextval('technologies_id_seq'::regclass), 'Analytica'),
       (nextval('technologies_id_seq'::regclass), 'Android Mini PC MK802'),
       (nextval('technologies_id_seq'::regclass), 'Ant'),
       (nextval('technologies_id_seq'::regclass), 'ANTLR'),
       (nextval('technologies_id_seq'::regclass), 'Apache Click'),
       (nextval('technologies_id_seq'::regclass), 'Apache Cocoon'),
       (nextval('technologies_id_seq'::regclass), 'Apache Cordova'),
       (nextval('technologies_id_seq'::regclass), 'Apache Flex'),
       (nextval('technologies_id_seq'::regclass), 'Apache Groovy'),
       (nextval('technologies_id_seq'::regclass), 'Apache Lenya'),
       (nextval('technologies_id_seq'::regclass), 'Apache OFBiz'),
       (nextval('technologies_id_seq'::regclass), 'Apache Roller'),
       (nextval('technologies_id_seq'::regclass), 'Apache Shale'),
       (nextval('technologies_id_seq'::regclass), 'Apache Sling'),
       (nextval('technologies_id_seq'::regclass), 'Apache Struts 1'),
       (nextval('technologies_id_seq'::regclass), 'Apache Struts 2'),
       (nextval('technologies_id_seq'::regclass), 'Apache Tapestry'),
       (nextval('technologies_id_seq'::regclass), 'Apache Wicket'),
       (nextval('technologies_id_seq'::regclass), 'Apigility'),
       (nextval('technologies_id_seq'::regclass), 'Apotomo'),
       (nextval('technologies_id_seq'::regclass), 'Appcelerator'),
       (nextval('technologies_id_seq'::regclass), 'Appcelerator Titanium'),
       (nextval('technologies_id_seq'::regclass), 'AppFuse'),
       (nextval('technologies_id_seq'::regclass), 'Appian'),
       (nextval('technologies_id_seq'::regclass), 'Applesoft BASIC'),
       (nextval('technologies_id_seq'::regclass), 'APT'),
       (nextval('technologies_id_seq'::regclass), 'ARB assembly language'),
       (nextval('technologies_id_seq'::regclass), 'Archivarix CMS'),
       (nextval('technologies_id_seq'::regclass), 'ArduCopter'),
       (nextval('technologies_id_seq'::regclass), 'Argus'),
       (nextval('technologies_id_seq'::regclass), 'ARITH-MATIC'),
       (nextval('technologies_id_seq'::regclass), 'ARM'),
       (nextval('technologies_id_seq'::regclass), 'Arndale Board'),
       (nextval('technologies_id_seq'::regclass), 'Artspeak'),
       (nextval('technologies_id_seq'::regclass), 'AS1'),
       (nextval('technologies_id_seq'::regclass), 'AS2'),
       (nextval('technologies_id_seq'::regclass), 'AS3'),
       (nextval('technologies_id_seq'::regclass), 'ASP.NET Core'),
       (nextval('technologies_id_seq'::regclass), 'ASP.NET Dynamic Data'),
       (nextval('technologies_id_seq'::regclass), 'ASP.NET MVC'),
       (nextval('technologies_id_seq'::regclass), 'ASP.NET Razor'),
       (nextval('technologies_id_seq'::regclass), 'ASP.NET Web Forms'),
       (nextval('technologies_id_seq'::regclass), 'Asus Tinker Board'),
       (nextval('technologies_id_seq'::regclass), 'Ateji PX'),
       (nextval('technologies_id_seq'::regclass), 'ATL Server'),
       (nextval('technologies_id_seq'::regclass), 'Atlas Autocode'),
       (nextval('technologies_id_seq'::regclass), 'ATS'),
       (nextval('technologies_id_seq'::regclass), 'ATutor'),
       (nextval('technologies_id_seq'::regclass), 'Audit Command Language'),
       (nextval('technologies_id_seq'::regclass), 'Autocode'),
       (nextval('technologies_id_seq'::regclass), 'AutoHotkey'),
       (nextval('technologies_id_seq'::regclass), 'Averest'),
       (nextval('technologies_id_seq'::regclass), 'Awesome CSS'),
       (nextval('technologies_id_seq'::regclass), 'AXIOM'),
       (nextval('technologies_id_seq'::regclass), 'B'),
       (nextval('technologies_id_seq'::regclass), 'b2evolution'),
       (nextval('technologies_id_seq'::regclass), 'Ballerina'),
       (nextval('technologies_id_seq'::regclass), 'Banana Pi'),
       (nextval('technologies_id_seq'::regclass), 'Barracuda'),
       (nextval('technologies_id_seq'::regclass), 'Base One Foundation Component Library'),
       (nextval('technologies_id_seq'::regclass), 'Batch file'),
       (nextval('technologies_id_seq'::regclass), 'BBj'),
       (nextval('technologies_id_seq'::regclass), 'BeagleBoard'),
       (nextval('technologies_id_seq'::regclass), 'BeanShell'),
       (nextval('technologies_id_seq'::regclass), 'Beatnik'),
       (nextval('technologies_id_seq'::regclass), 'BEdita'),
       (nextval('technologies_id_seq'::regclass), 'Befunge'),
       (nextval('technologies_id_seq'::regclass), 'Ben NanoNote'),
       (nextval('technologies_id_seq'::regclass), 'BetterCMS'),
       (nextval('technologies_id_seq'::regclass), 'Bindows'),
       (nextval('technologies_id_seq'::regclass), 'Birkbeck Assembler'),
       (nextval('technologies_id_seq'::regclass), 'BitC'),
       (nextval('technologies_id_seq'::regclass), 'Bizagi'),
       (nextval('technologies_id_seq'::regclass), 'Blend4Web'),
       (nextval('technologies_id_seq'::regclass), 'BLISS'),
       (nextval('technologies_id_seq'::regclass), 'Blitz Basic'),
       (nextval('technologies_id_seq'::regclass), 'BlitzBasic'),
       (nextval('technologies_id_seq'::regclass), 'Blockly'),
       (nextval('technologies_id_seq'::regclass), 'blosxom'),
       (nextval('technologies_id_seq'::regclass), 'Blue'),
       (nextval('technologies_id_seq'::regclass), 'BlueBream'),
       (nextval('technologies_id_seq'::regclass), 'Bluespec'),
       (nextval('technologies_id_seq'::regclass), 'BMDFM'),
       (nextval('technologies_id_seq'::regclass), 'Boehm unnamed coding system'),
       (nextval('technologies_id_seq'::regclass), 'Bottle'),
       (nextval('technologies_id_seq'::regclass), 'Boundary Devices'),
       (nextval('technologies_id_seq'::regclass), 'Brainfuck'),
       (nextval('technologies_id_seq'::regclass), 'Bricolage'),
       (nextval('technologies_id_seq'::regclass), 'Bro'),
       (nextval('technologies_id_seq'::regclass), 'Brutos Framework'),
       (nextval('technologies_id_seq'::regclass), 'C Sharp'),
       (nextval('technologies_id_seq'::regclass), 'C#.NET'),
       (nextval('technologies_id_seq'::regclass), 'C-Sharp'),
       (nextval('technologies_id_seq'::regclass), 'C/AL'),
       (nextval('technologies_id_seq'::regclass), 'C/AL (C/SIDE)'),
       (nextval('technologies_id_seq'::regclass), 'C1 CMS'),
       (nextval('technologies_id_seq'::regclass), 'CA-Telon'),
       (nextval('technologies_id_seq'::regclass), 'Caché'),
       (nextval('technologies_id_seq'::regclass), 'CakePHP'),
       (nextval('technologies_id_seq'::regclass), 'CAL'),
       (nextval('technologies_id_seq'::regclass), 'CAL Actor Language'),
       (nextval('technologies_id_seq'::regclass), 'Camping'),
       (nextval('technologies_id_seq'::regclass), 'Cardinal'),
       (nextval('technologies_id_seq'::regclass), 'Castle Project'),
       (nextval('technologies_id_seq'::regclass), 'Catalyst'),
       (nextval('technologies_id_seq'::regclass), 'Caveman2'),
       (nextval('technologies_id_seq'::regclass), 'CBASIC'),
       (nextval('technologies_id_seq'::regclass), 'Cecil'),
       (nextval('technologies_id_seq'::regclass), 'Ceylon Project'),
       (nextval('technologies_id_seq'::regclass), 'Cgiapp'),
       (nextval('technologies_id_seq'::regclass), 'Charity'),
       (nextval('technologies_id_seq'::regclass), 'Charm'),
       (nextval('technologies_id_seq'::regclass), 'Chef'),
       (nextval('technologies_id_seq'::regclass), 'CherryPy'),
       (nextval('technologies_id_seq'::regclass), 'Chinese BASIC'),
       (nextval('technologies_id_seq'::regclass), 'ChucK'),
       (nextval('technologies_id_seq'::regclass), 'Chumby'),
       (nextval('technologies_id_seq'::regclass), 'Cilk'),
       (nextval('technologies_id_seq'::regclass), 'CL'),
       (nextval('technologies_id_seq'::regclass), 'CLACL'),
       (nextval('technologies_id_seq'::regclass), 'Claire'),
       (nextval('technologies_id_seq'::regclass), 'Clarion Programming Language'),
       (nextval('technologies_id_seq'::regclass), 'Clascal'),
       (nextval('technologies_id_seq'::regclass), 'CLEO'),
       (nextval('technologies_id_seq'::regclass), 'CLIPPER 5.3'),
       (nextval('technologies_id_seq'::regclass), 'CLIPS'),
       (nextval('technologies_id_seq'::regclass), 'CLIST'),
       (nextval('technologies_id_seq'::regclass), 'CLLE'),
       (nextval('technologies_id_seq'::regclass), 'ClojureScript'),
       (nextval('technologies_id_seq'::regclass), 'CMS EXEC'),
       (nextval('technologies_id_seq'::regclass), 'CMS Made Simple'),
       (nextval('technologies_id_seq'::regclass), 'CMSimple'),
       (nextval('technologies_id_seq'::regclass), 'Co-array Fortran'),
       (nextval('technologies_id_seq'::regclass), 'Coco/R'),
       (nextval('technologies_id_seq'::regclass), 'Cocoa'),
       (nextval('technologies_id_seq'::regclass), 'CocoonJS'),
       (nextval('technologies_id_seq'::regclass), 'CodeCharge Studio'),
       (nextval('technologies_id_seq'::regclass), 'CodeGear Delphi'),
       (nextval('technologies_id_seq'::regclass), 'CodeIgniter'),
       (nextval('technologies_id_seq'::regclass), 'Coderity'),
       (nextval('technologies_id_seq'::regclass), 'Cognos PowerHouse 4GL'),
       (nextval('technologies_id_seq'::regclass), 'ColdBox Platform'),
       (nextval('technologies_id_seq'::regclass), 'ColdFusion'),
       (nextval('technologies_id_seq'::regclass), 'ColdFusion Markup Language'),
       (nextval('technologies_id_seq'::regclass), 'ColdFusion on Wheels'),
       (nextval('technologies_id_seq'::regclass), 'ColdSpring'),
       (nextval('technologies_id_seq'::regclass), 'ColdSpring Framework'),
       (nextval('technologies_id_seq'::regclass), 'colorForth'),
       (nextval('technologies_id_seq'::regclass), 'Combined Programming Language'),
       (nextval('technologies_id_seq'::regclass), 'Comet'),
       (nextval('technologies_id_seq'::regclass), 'COMIT'),
       (nextval('technologies_id_seq'::regclass), 'Commodore BASIC'),
       (nextval('technologies_id_seq'::regclass), 'Comparison of JavaScript frameworks'),
       (nextval('technologies_id_seq'::regclass), 'Compiler Description Language'),
       (nextval('technologies_id_seq'::regclass), 'Component Pascal'),
       (nextval('technologies_id_seq'::regclass), 'Component-based Scalable Logical Architecture'),
       (nextval('technologies_id_seq'::regclass), 'COMPOOL'),
       (nextval('technologies_id_seq'::regclass), 'Composr CMS'),
       (nextval('technologies_id_seq'::regclass), 'COMTRAN'),
       (nextval('technologies_id_seq'::regclass), 'Concise CSS'),
       (nextval('technologies_id_seq'::regclass), 'concrete5'),
       (nextval('technologies_id_seq'::regclass), 'Concurrent Pascal'),
       (nextval('technologies_id_seq'::regclass), 'Confluence'),
       (nextval('technologies_id_seq'::regclass), 'Constraint Handling Rules'),
       (nextval('technologies_id_seq'::regclass), 'Contao'),
       (nextval('technologies_id_seq'::regclass), 'ContentBox Modular CMS'),
       (nextval('technologies_id_seq'::regclass), 'Coq'),
       (nextval('technologies_id_seq'::regclass), 'Coral 66'),
       (nextval('technologies_id_seq'::regclass), 'Core War'),
       (nextval('technologies_id_seq'::regclass), 'CorVision'),
       (nextval('technologies_id_seq'::regclass), 'COWSEL'),
       (nextval('technologies_id_seq'::regclass), 'cpp'),
       (nextval('technologies_id_seq'::regclass), 'CppCMS'),
       (nextval('technologies_id_seq'::regclass), 'Crafter CMS'),
       (nextval('technologies_id_seq'::regclass), 'Crosswalk Project'),
       (nextval('technologies_id_seq'::regclass), 'Crypton'),
       (nextval('technologies_id_seq'::regclass), 'crystallang'),
       (nextval('technologies_id_seq'::regclass), 'CS-4'),
       (nextval('technologies_id_seq'::regclass), 'CSC'),
       (nextval('technologies_id_seq'::regclass), 'csh'),
       (nextval('technologies_id_seq'::regclass), 'CSharp'),
       (nextval('technologies_id_seq'::regclass), 'CSharp.NET'),
       (nextval('technologies_id_seq'::regclass), 'CubicWeb'),
       (nextval('technologies_id_seq'::regclass), 'Cubieboard'),
       (nextval('technologies_id_seq'::regclass), 'CUBIT'),
       (nextval('technologies_id_seq'::regclass), 'Culprit'),
       (nextval('technologies_id_seq'::regclass), 'Cuneiform'),
       (nextval('technologies_id_seq'::regclass), 'Curry'),
       (nextval('technologies_id_seq'::regclass), 'Cutestrap'),
       (nextval('technologies_id_seq'::regclass), 'CWIC'),
       (nextval('technologies_id_seq'::regclass), 'Cyclone'),
       (nextval('technologies_id_seq'::regclass), 'Cython'),
       (nextval('technologies_id_seq'::regclass), 'Cω'),
       (nextval('technologies_id_seq'::regclass), 'Dabble DB'),
       (nextval('technologies_id_seq'::regclass), 'Dafny'),
       (nextval('technologies_id_seq'::regclass), 'Daisy'),
       (nextval('technologies_id_seq'::regclass), 'Dancer'),
       (nextval('technologies_id_seq'::regclass), 'DarkBASIC'),
       (nextval('technologies_id_seq'::regclass), 'DASL'),
       (nextval('technologies_id_seq'::regclass), 'DATABUS'),
       (nextval('technologies_id_seq'::regclass), 'DataFlex'),
       (nextval('technologies_id_seq'::regclass), 'dBase'),
       (nextval('technologies_id_seq'::regclass), 'DBL'),
       (nextval('technologies_id_seq'::regclass), 'DEC'),
       (nextval('technologies_id_seq'::regclass), 'DEC Alpha'),
       (nextval('technologies_id_seq'::regclass), 'Delphi'),
       (nextval('technologies_id_seq'::regclass), 'Delphi.NET'),
       (nextval('technologies_id_seq'::regclass), 'DirectX High-Level Shading Language'),
       (nextval('technologies_id_seq'::regclass), 'DITA'),
       (nextval('technologies_id_seq'::regclass), 'django CMS'),
       (nextval('technologies_id_seq'::regclass), 'dlang'),
       (nextval('technologies_id_seq'::regclass), 'DM'),
       (nextval('technologies_id_seq'::regclass), 'DokuWiki'),
       (nextval('technologies_id_seq'::regclass), 'DOS batch language'),
       (nextval('technologies_id_seq'::regclass), 'Dotclear'),
       (nextval('technologies_id_seq'::regclass), 'dotCMS'),
       (nextval('technologies_id_seq'::regclass), 'DotNetNuke'),
       (nextval('technologies_id_seq'::regclass), 'Draco'),
       (nextval('technologies_id_seq'::regclass), 'DRAKON'),
       (nextval('technologies_id_seq'::regclass), 'DreamPlug'),
       (nextval('technologies_id_seq'::regclass), 'Drools'),
       (nextval('technologies_id_seq'::regclass), 'DSpace'),
       (nextval('technologies_id_seq'::regclass), 'DwScript'),
       (nextval('technologies_id_seq'::regclass), 'e-puck mobile robot'),
       (nextval('technologies_id_seq'::regclass), 'Easytrieve'),
       (nextval('technologies_id_seq'::regclass), 'eC'),
       (nextval('technologies_id_seq'::regclass), 'Echo Framework'),
       (nextval('technologies_id_seq'::regclass), 'ECL'),
       (nextval('technologies_id_seq'::regclass), 'ECLiPSe'),
       (nextval('technologies_id_seq'::regclass), 'ECMAScript for XML'),
       (nextval('technologies_id_seq'::regclass), 'Edinburgh IMP'),
       (nextval('technologies_id_seq'::regclass), 'Editing Generator'),
       (nextval('technologies_id_seq'::regclass), 'EEL'),
       (nextval('technologies_id_seq'::regclass), 'EICASLAB'),
       (nextval('technologies_id_seq'::regclass), 'Elan'),
       (nextval('technologies_id_seq'::regclass), 'Elips'),
       (nextval('technologies_id_seq'::regclass), 'ELLA'),
       (nextval('technologies_id_seq'::regclass), 'Elphel, Inc.'),
       (nextval(' technologies_id_seq '::regclass), ' Enonic XP '),
       (nextval(' technologies_id_seq '::regclass), ' EPrints '),
       (nextval(' technologies_id_seq '::regclass), ' Esterel '),
       (nextval(' technologies_id_seq '::regclass), ' ESys.net '),
       (nextval(' technologies_id_seq '::regclass), ' Ethernut '),
       (nextval(' technologies_id_seq '::regclass), ' Euclid '),
       (nextval(' technologies_id_seq '::regclass), ' Euler '),
       (nextval(' technologies_id_seq '::regclass), ' EuLisp '),
       (nextval(' technologies_id_seq '::regclass), ' EXAPT '),
       (nextval(' technologies_id_seq '::regclass), ' EXEC 2'),
       (nextval('technologies_id_seq'::regclass), 'expanz'),
       (nextval('technologies_id_seq'::regclass), 'Expect'),
       (nextval('technologies_id_seq'::regclass), 'Exponent CMS'),
       (nextval('technologies_id_seq'::regclass), 'Express.js'),
       (nextval('technologies_id_seq'::regclass), 'ExtJS'),
       (nextval('technologies_id_seq'::regclass), 'eZ Platform'),
       (nextval('technologies_id_seq'::regclass), 'eZ Publish'),
       (nextval('technologies_id_seq'::regclass), 'ezhil'),
       (nextval('technologies_id_seq'::regclass), 'F'),
       (nextval('technologies_id_seq'::regclass), 'F Sharp'),
       (nextval('technologies_id_seq'::regclass), 'F-Script'),
       (nextval('technologies_id_seq'::regclass), 'F-Sharp'),
       (nextval('technologies_id_seq'::regclass), 'Fabrik'),
       (nextval('technologies_id_seq'::regclass), 'FACT computer language'),
       (nextval('technologies_id_seq'::regclass), 'FarCry CMS'),
       (nextval('technologies_id_seq'::regclass), 'Fat-Free Framework'),
       (nextval('technologies_id_seq'::regclass), 'Fedora Commons'),
       (nextval('technologies_id_seq'::regclass), 'FHTML'),
       (nextval('technologies_id_seq'::regclass), 'Filetab'),
       (nextval('technologies_id_seq'::regclass), 'fish'),
       (nextval('technologies_id_seq'::regclass), 'Fjölnir'),
       (nextval('technologies_id_seq'::regclass), 'Flexive'),
       (nextval('technologies_id_seq'::regclass), 'FLOW-MATIC'),
       (nextval('technologies_id_seq'::regclass), 'Fluid UI'),
       (nextval('technologies_id_seq'::regclass), 'FOCUS'),
       (nextval('technologies_id_seq'::regclass), 'FormEngine'),
       (nextval('technologies_id_seq'::regclass), 'Fortran 2003'),
       (nextval('technologies_id_seq'::regclass), 'Fortran 66'),
       (nextval('technologies_id_seq'::regclass), 'Fortran 77'),
       (nextval('technologies_id_seq'::regclass), 'Fortran 90'),
       (nextval('technologies_id_seq'::regclass), 'Fortran I'),
       (nextval('technologies_id_seq'::regclass), 'Forté TOOL'),
       (nextval('technologies_id_seq'::regclass), 'Foswiki'),
       (nextval('technologies_id_seq'::regclass), 'Fox Pro'),
       (nextval('technologies_id_seq'::regclass), 'FoxPro'),
       (nextval('technologies_id_seq'::regclass), 'FP'),
       (nextval('technologies_id_seq'::regclass), 'Freddy II'),
       (nextval('technologies_id_seq'::regclass), 'Free Pascal'),
       (nextval('technologies_id_seq'::regclass), 'FreeBASIC'),
       (nextval('technologies_id_seq'::regclass), 'Freeduino'),
       (nextval('technologies_id_seq'::regclass), 'Freemat'),
       (nextval('technologies_id_seq'::regclass), 'Freiburger Code'),
       (nextval('technologies_id_seq'::regclass), 'FriendlyElec'),
       (nextval('technologies_id_seq'::regclass), 'Fril'),
       (nextval('technologies_id_seq'::regclass), 'FSharp'),
       (nextval('technologies_id_seq'::regclass), 'FuelPHP'),
       (nextval('technologies_id_seq'::regclass), 'Furatto'),
       (nextval('technologies_id_seq'::regclass), 'Furtive'),
       (nextval('technologies_id_seq'::regclass), 'Fusebox'),
       (nextval('technologies_id_seq'::regclass), 'Game Maker Language'),
       (nextval('technologies_id_seq'::regclass), 'GameMaker Language'),
       (nextval('technologies_id_seq'::regclass), 'GameStick'),
       (nextval('technologies_id_seq'::regclass), 'GAMS'),
       (nextval('technologies_id_seq'::regclass), 'Gatsby'),
       (nextval('technologies_id_seq'::regclass), 'GAUSS'),
       (nextval('technologies_id_seq'::regclass), 'Gawk'),
       (nextval('technologies_id_seq'::regclass), 'GDScript'),
       (nextval('technologies_id_seq'::regclass), 'Geeklog'),
       (nextval('technologies_id_seq'::regclass), 'Gelatos Shading Language'),
       (nextval('technologies_id_seq'::regclass), 'GeneXus'),
       (nextval('technologies_id_seq'::regclass), 'Genie'),
       (nextval('technologies_id_seq'::regclass), 'GEORGE'),
       (nextval('technologies_id_seq'::regclass), 'GetSimple CMS'),
       (nextval('technologies_id_seq'::regclass), 'GFA BASIC'),
       (nextval('technologies_id_seq'::regclass), 'Ghost'),
       (nextval('technologies_id_seq'::regclass), 'GLBasic'),
       (nextval('technologies_id_seq'::regclass), 'GNU bison'),
       (nextval('technologies_id_seq'::regclass), 'GNU E'),
       (nextval('technologies_id_seq'::regclass), 'GOAL agent programming language'),
       (nextval('technologies_id_seq'::regclass), 'Golang'),
       (nextval('technologies_id_seq'::regclass), 'Google Apps Script'),
       (nextval('technologies_id_seq'::regclass), 'Google Closure Tools'),
       (nextval('technologies_id_seq'::regclass), 'GoWarrior'),
       (nextval('technologies_id_seq'::regclass), 'GPATH'),
       (nextval('technologies_id_seq'::regclass), 'Grails'),
       (nextval('technologies_id_seq'::regclass), 'GraphTalk'),
       (nextval('technologies_id_seq'::regclass), 'GRASS'),
       (nextval('technologies_id_seq'::regclass), 'Grav'),
       (nextval('technologies_id_seq'::regclass), 'Grok'),
       (nextval('technologies_id_seq'::regclass), 'Groovy++'),
       (nextval('technologies_id_seq'::regclass), 'GSQL'),
       (nextval('technologies_id_seq'::regclass), 'Guile'),
       (nextval('technologies_id_seq'::regclass), 'GW-BASIC'),
       (nextval('technologies_id_seq'::regclass), 'Gyroscope'),
       (nextval('technologies_id_seq'::regclass), 'Habari'),
       (nextval('technologies_id_seq'::regclass), 'HAL/S'),
       (nextval('technologies_id_seq'::regclass), 'Hamilton C shell'),
       (nextval('technologies_id_seq'::regclass), 'Hamlets'),
       (nextval('technologies_id_seq'::regclass), 'Hammerkit'),
       (nextval('technologies_id_seq'::regclass), 'Handel-C'),
       (nextval('technologies_id_seq'::regclass), 'Harbour'),
       (nextval('technologies_id_seq'::regclass), 'Hartmann pipeline'),
       (nextval('technologies_id_seq'::regclass), 'HHDL'),
       (nextval('technologies_id_seq'::regclass), 'HiFive Unleashed'),
       (nextval('technologies_id_seq'::regclass), 'HiFive1'),
       (nextval('technologies_id_seq'::regclass), 'High Level Assembly'),
       (nextval('technologies_id_seq'::regclass), 'Hippo CMS'),
       (nextval('technologies_id_seq'::regclass), 'Hop'),
       (nextval('technologies_id_seq'::regclass), 'Hope'),
       (nextval('technologies_id_seq'::regclass), 'Horde'),
       (nextval('technologies_id_seq'::regclass), 'Html KickStart'),
       (nextval('technologies_id_seq'::regclass), 'Hugo'),
       (nextval('technologies_id_seq'::regclass), 'HyperNext'),
       (nextval('technologies_id_seq'::regclass), 'IA-32'),
       (nextval('technologies_id_seq'::regclass), 'IAd Producer'),
       (nextval('technologies_id_seq'::regclass), 'IBM BASICA'),
       (nextval('technologies_id_seq'::regclass), 'IBM Informix-4GL'),
       (nextval('technologies_id_seq'::regclass), 'IBM NetRexx'),
       (nextval('technologies_id_seq'::regclass), 'IBM RPG'),
       (nextval('technologies_id_seq'::regclass), 'IBM System/360'),
       (nextval('technologies_id_seq'::regclass), 'IBM VisualAge'),
       (nextval('technologies_id_seq'::regclass), 'IBM WebSphere Application Server'),
       (nextval('technologies_id_seq'::regclass), 'IBM WebSphere Application Server Community Edition'),
       (nextval('technologies_id_seq'::regclass), 'ICEfaces'),
       (nextval('technologies_id_seq'::regclass), 'ICI'),
       (nextval('technologies_id_seq'::regclass), 'ICub'),
       (nextval('technologies_id_seq'::regclass), 'IGEPv2'),
       (nextval('technologies_id_seq'::regclass), 'IGOR Pro'),
       (nextval('technologies_id_seq'::regclass), 'IITRAN'),
       (nextval('technologies_id_seq'::regclass), 'Ikiwiki'),
       (nextval('technologies_id_seq'::regclass), 'ILERPG'),
       (nextval('technologies_id_seq'::regclass), 'ImpressCMS'),
       (nextval('technologies_id_seq'::regclass), 'ImpressPages'),
       (nextval('technologies_id_seq'::regclass), 'Impulse C'),
       (nextval('technologies_id_seq'::regclass), 'INEK'),
       (nextval('technologies_id_seq'::regclass), 'Information Processing Language'),
       (nextval('technologies_id_seq'::regclass), 'Ink'),
       (nextval('technologies_id_seq'::regclass), 'Integer BASIC'),
       (nextval('technologies_id_seq'::regclass), 'Intel'),
       (nextval('technologies_id_seq'::regclass), 'Intel 80186'),
       (nextval('technologies_id_seq'::regclass), 'Intel 80286'),
       (nextval('technologies_id_seq'::regclass), 'Intel 8086'),
       (nextval('technologies_id_seq'::regclass), 'Intel Galileo'),
       (nextval('technologies_id_seq'::regclass), 'Interlisp'),
       (nextval('technologies_id_seq'::regclass), 'Internal Translator'),
       (nextval('technologies_id_seq'::regclass), 'International Federation for Information Processing'),
       (nextval('technologies_id_seq'::regclass), 'Inuit CSS'),
       (nextval('technologies_id_seq'::regclass), 'IOIO'),
       (nextval('technologies_id_seq'::regclass), 'Ionic'),
       (nextval('technologies_id_seq'::regclass), 'iPFaces mobile framework'),
       (nextval('technologies_id_seq'::regclass), 'IPL-v'),
       (nextval('technologies_id_seq'::regclass), 'Irvine Dataflow'),
       (nextval('technologies_id_seq'::regclass), 'ISLISP'),
       (nextval('technologies_id_seq'::regclass), 'ISWIM'),
       (nextval('technologies_id_seq'::regclass), 'ItsNat'),
       (nextval('technologies_id_seq'::regclass), 'Jahia'),
       (nextval('technologies_id_seq'::regclass), 'Jamroom'),
       (nextval('technologies_id_seq'::regclass), 'Janus'),
       (nextval('technologies_id_seq'::regclass), 'JASS'),
       (nextval('technologies_id_seq'::regclass), 'Java Platform, Enterprise Edition'),
       (nextval('technologies_id_seq'::regclass), 'JavaCC'),
       (nextval('technologies_id_seq'::regclass), 'JavaFX'),
       (nextval('technologies_id_seq'::regclass), 'JavaPoly'),
       (nextval('technologies_id_seq'::regclass), 'JavaServer Faces'),
       (nextval('technologies_id_seq'::regclass), 'JBND'),
       (nextval('technologies_id_seq'::regclass), 'JBoss Seam'),
       (nextval('technologies_id_seq'::regclass), 'JCL'),
       (nextval('technologies_id_seq'::regclass), 'Jess'),
       (nextval('technologies_id_seq'::regclass), 'JHDL'),
       (nextval('technologies_id_seq'::regclass), 'JHipster'),
       (nextval('technologies_id_seq'::regclass), 'JMP'),
       (nextval('technologies_id_seq'::regclass), 'Join Java'),
       (nextval('technologies_id_seq'::regclass), 'Joomla'),
       (nextval('technologies_id_seq'::regclass), 'Joomla!'),
       (nextval('technologies_id_seq'::regclass), 'JOSS'),
       (nextval('technologies_id_seq'::regclass), 'Joule'),
       (nextval('technologies_id_seq'::regclass), 'JOVIAL'),
       (nextval('technologies_id_seq'::regclass), 'Joy'),
       (nextval('technologies_id_seq'::regclass), 'JS'),
       (nextval('technologies_id_seq'::regclass), 'JS++'),
       (nextval('technologies_id_seq'::regclass), 'JSL'),
       (nextval('technologies_id_seq'::regclass), 'Jspx-bay'),
       (nextval('technologies_id_seq'::regclass), 'julia-lang'),
       (nextval('technologies_id_seq'::regclass), 'Julialang'),
       (nextval('technologies_id_seq'::regclass), 'JVx'),
       (nextval('technologies_id_seq'::regclass), 'JWt'),
       (nextval('technologies_id_seq'::regclass), 'K'),
       (nextval('technologies_id_seq'::regclass), 'K2'),
       (nextval('technologies_id_seq'::regclass), 'Kajona'),
       (nextval('technologies_id_seq'::regclass), 'Kentico CMS'),
       (nextval('technologies_id_seq'::regclass), 'Kepler'),
       (nextval('technologies_id_seq'::regclass), 'Kitura'),
       (nextval('technologies_id_seq'::regclass), 'Klammerausdrücke'),
       (nextval('technologies_id_seq'::regclass), 'Klerer-May System'),
       (nextval('technologies_id_seq'::regclass), 'KnockoutJS'),
       (nextval('technologies_id_seq'::regclass), 'Known'),
       (nextval('technologies_id_seq'::regclass), 'Kohana'),
       (nextval('technologies_id_seq'::regclass), 'Kony'),
       (nextval('technologies_id_seq'::regclass), 'Kraken'),
       (nextval('technologies_id_seq'::regclass), 'KRC'),
       (nextval('technologies_id_seq'::regclass), 'KRL'),
       (nextval('technologies_id_seq'::regclass), 'ksh'),
       (nextval('technologies_id_seq'::regclass), 'KTurtle'),
       (nextval('technologies_id_seq'::regclass), 'Kube'),
       (nextval('technologies_id_seq'::regclass), 'Laning and Zierler system'),
       (nextval('technologies_id_seq'::regclass), 'LANSA'),
       (nextval('technologies_id_seq'::regclass), 'Lava'),
       (nextval('technologies_id_seq'::regclass), 'Leda'),
       (nextval('technologies_id_seq'::regclass), 'LEON'),
       (nextval('technologies_id_seq'::regclass), 'lex'),
       (nextval('technologies_id_seq'::regclass), 'Lexico'),
       (nextval('technologies_id_seq'::regclass), 'LFE'),
       (nextval('technologies_id_seq'::regclass), 'Li3'),
       (nextval('technologies_id_seq'::regclass), 'Libre Computer Project'),
       (nextval('technologies_id_seq'::regclass), 'Lift'),
       (nextval('technologies_id_seq'::regclass), 'Lime'),
       (nextval('technologies_id_seq'::regclass), 'Limnor'),
       (nextval('technologies_id_seq'::regclass), 'Linaro Community Board Group'),
       (nextval('technologies_id_seq'::regclass), 'LINC'),
       (nextval('technologies_id_seq'::regclass), 'LINC 4GL'),
       (nextval('technologies_id_seq'::regclass), 'Linden Scripting Language'),
       (nextval('technologies_id_seq'::regclass), 'LIRC'),
       (nextval('technologies_id_seq'::regclass), 'LIS'),
       (nextval('technologies_id_seq'::regclass), 'Little b'),
       (nextval('technologies_id_seq'::regclass), 'Little Smalltalk'),
       (nextval('technologies_id_seq'::regclass), 'LogicalDOC'),
       (nextval('technologies_id_seq'::regclass), 'Logtalk'),
       (nextval('technologies_id_seq'::regclass), 'Lola'),
       (nextval('technologies_id_seq'::regclass), 'LOLCODE'),
       (nextval('technologies_id_seq'::regclass), 'LuaJIT'),
       (nextval('technologies_id_seq'::regclass), 'Lucid'),
       (nextval('technologies_id_seq'::regclass), 'Lumen'),
       (nextval('technologies_id_seq'::regclass), 'LZX'),
       (nextval('technologies_id_seq'::regclass), 'M'),
       (nextval('technologies_id_seq'::regclass), 'M#'),
       (nextval('technologies_id_seq'::regclass), 'M2001'),
       (nextval('technologies_id_seq'::regclass), 'Machine language'),
       (nextval('technologies_id_seq'::regclass), 'Magento'),
       (nextval('technologies_id_seq'::regclass), 'Magnolia'),
       (nextval('technologies_id_seq'::regclass), 'MAI Basic Four'),
       (nextval('technologies_id_seq'::regclass), 'Mambo'),
       (nextval('technologies_id_seq'::regclass), 'MAPPER'),
       (nextval('technologies_id_seq'::regclass), 'MARK IV'),
       (nextval('technologies_id_seq'::regclass), 'MARK-IV'),
       (nextval('technologies_id_seq'::regclass), 'Mason'),
       (nextval('technologies_id_seq'::regclass), 'MATH-MATIC'),
       (nextval('technologies_id_seq'::regclass), 'Mathematica'),
       (nextval('technologies_id_seq'::regclass), 'MathProg'),
       (nextval('technologies_id_seq'::regclass), 'MATRIX MATH'),
       (nextval('technologies_id_seq'::regclass), 'Maude system'),
       (nextval('technologies_id_seq'::regclass), 'Mawk'),
       (nextval('technologies_id_seq'::regclass), 'Max'),
       (nextval('technologies_id_seq'::regclass), 'Maypole framework'),
       (nextval('technologies_id_seq'::regclass), 'MCST'),
       (nextval('technologies_id_seq'::regclass), 'MediaTek'),
       (nextval('technologies_id_seq'::regclass), 'MediaWiki'),
       (nextval('technologies_id_seq'::regclass), 'Mendix'),
       (nextval('technologies_id_seq'::regclass), 'Merb'),
       (nextval('technologies_id_seq'::regclass), 'Mesa'),
       (nextval('technologies_id_seq'::regclass), 'META I'),
       (nextval('technologies_id_seq'::regclass), 'META II'),
       (nextval('technologies_id_seq'::regclass), 'Metal Shading Language'),
       (nextval('technologies_id_seq'::regclass), 'Metaobject protocols'),
       (nextval('technologies_id_seq'::regclass), 'MetaOCaml'),
       (nextval('technologies_id_seq'::regclass), 'MetaPost'),
       (nextval('technologies_id_seq'::regclass), 'Mezzanine'),
       (nextval('technologies_id_seq'::regclass), 'MiaCMS'),
       (nextval('technologies_id_seq'::regclass), 'Microsoft Small Basic'),
       (nextval('technologies_id_seq'::regclass), 'Microweber'),
       (nextval('technologies_id_seq'::regclass), 'Midgard'),
       (nextval('technologies_id_seq'::regclass), 'MIMIC'),
       (nextval('technologies_id_seq'::regclass), 'Mini CSS'),
       (nextval('technologies_id_seq'::regclass), 'MiniD'),
       (nextval('technologies_id_seq'::regclass), 'Minimig'),
       (nextval('technologies_id_seq'::regclass), 'MIPS'),
       (nextval('technologies_id_seq'::regclass), 'MIPS Creator'),
       (nextval('technologies_id_seq'::regclass), 'Miranda'),
       (nextval('technologies_id_seq'::regclass), 'ML/I'),
       (nextval('technologies_id_seq'::regclass), 'Mobi CSS'),
       (nextval('technologies_id_seq'::regclass), 'Model-Glue'),
       (nextval('technologies_id_seq'::regclass), 'Modelica'),
       (nextval('technologies_id_seq'::regclass), 'ModernPascal'),
       (nextval('technologies_id_seq'::regclass), 'Modula'),
       (nextval('technologies_id_seq'::regclass), 'MODX'),
       (nextval('technologies_id_seq'::regclass), 'MoinMoin'),
       (nextval('technologies_id_seq'::regclass), 'Mojolicious'),
       (nextval('technologies_id_seq'::regclass), 'mojoPortal'),
       (nextval('technologies_id_seq'::regclass), 'Monkey X'),
       (nextval('technologies_id_seq'::regclass), 'MonoRail'),
       (nextval('technologies_id_seq'::regclass), 'Moobile.js'),
       (nextval('technologies_id_seq'::regclass), 'Morfik'),
       (nextval('technologies_id_seq'::regclass), 'MOS Technology'),
       (nextval('technologies_id_seq'::regclass), 'Motorola 6800'),
       (nextval('technologies_id_seq'::regclass), 'Movable Type'),
       (nextval('technologies_id_seq'::regclass), 'Mozilla Skywriter'),
       (nextval('technologies_id_seq'::regclass), 'MQL5'),
       (nextval('technologies_id_seq'::regclass), 'Mui CSS'),
       (nextval('technologies_id_seq'::regclass), 'MultiLisp'),
       (nextval('technologies_id_seq'::regclass), 'multiplo'),
       (nextval('technologies_id_seq'::regclass), 'Mura CMS'),
       (nextval('technologies_id_seq'::regclass), 'MXML'),
       (nextval('technologies_id_seq'::regclass), 'MyHDL'),
       (nextval('technologies_id_seq'::regclass), 'Nagare'),
       (nextval('technologies_id_seq'::regclass), 'Nawk'),
       (nextval('technologies_id_seq'::regclass), 'Netduino'),
       (nextval('technologies_id_seq'::regclass), 'NetRexx'),
       (nextval('technologies_id_seq'::regclass), 'Nette Framework'),
       (nextval('technologies_id_seq'::regclass), 'Netty'),
       (nextval('technologies_id_seq'::regclass), 'Nevow'),
       (nextval('technologies_id_seq'::regclass), 'NewtonScript'),
       (nextval('technologies_id_seq'::regclass), 'Nimrod'),
       (nextval('technologies_id_seq'::regclass), 'Nitrokey'),
       (nextval('technologies_id_seq'::regclass), 'NodeMCU'),
       (nextval('technologies_id_seq'::regclass), 'Nomad'),
       (nextval('technologies_id_seq'::regclass), 'Novena'),
       (nextval('technologies_id_seq'::regclass), 'Novius OS'),
       (nextval('technologies_id_seq'::regclass), 'NPL'),
       (nextval('technologies_id_seq'::regclass), 'Nucleus CMS'),
       (nextval('technologies_id_seq'::regclass), 'Nuxeo'),
       (nextval('technologies_id_seq'::regclass), 'Nvidia'),
       (nextval('technologies_id_seq'::regclass), 'Oberon-2'),
       (nextval('technologies_id_seq'::regclass), 'Obidos'),
       (nextval('technologies_id_seq'::regclass), 'obj-c'),
       (nextval('technologies_id_seq'::regclass), 'objc'),
       (nextval('technologies_id_seq'::regclass), 'Object Oberon'),
       (nextval('technologies_id_seq'::regclass), 'Object Pascal'),
       (nextval('technologies_id_seq'::regclass), 'Objective Caml'),
       (nextval('technologies_id_seq'::regclass), 'Obliq'),
       (nextval('technologies_id_seq'::regclass), 'occam-π'),
       (nextval('technologies_id_seq'::regclass), 'Ocsigen'),
       (nextval('technologies_id_seq'::regclass), 'Octave'),
       (nextval('technologies_id_seq'::regclass), 'October'),
       (nextval('technologies_id_seq'::regclass), 'Odroid'),
       (nextval('technologies_id_seq'::regclass), 'OLinuXino'),
       (nextval('technologies_id_seq'::regclass), 'Omega2'),
       (nextval('technologies_id_seq'::regclass), 'Omeka'),
       (nextval('technologies_id_seq'::regclass), 'OMNIBAC Symbolic Assembler'),
       (nextval('technologies_id_seq'::regclass), 'Omnis Studio'),
       (nextval('technologies_id_seq'::regclass), 'Opa'),
       (nextval('technologies_id_seq'::regclass), 'Opal'),
       (nextval('technologies_id_seq'::regclass), 'Open Programming Language'),
       (nextval('technologies_id_seq'::regclass), 'Open Semantic Framework'),
       (nextval('technologies_id_seq'::regclass), 'Open Shading Language'),
       (nextval('technologies_id_seq'::regclass), 'OpenCart'),
       (nextval('technologies_id_seq'::regclass), 'OpenCms'),
       (nextval('technologies_id_seq'::regclass), 'OpenEdge'),
       (nextval('technologies_id_seq'::regclass), 'Openframe'),
       (nextval('technologies_id_seq'::regclass), 'OpenGL Shading Language'),
       (nextval('technologies_id_seq'::regclass), 'OpenKM'),
       (nextval('technologies_id_seq'::regclass), 'OpenLaszlo'),
       (nextval('technologies_id_seq'::regclass), 'OpenLisp'),
       (nextval('technologies_id_seq'::regclass), 'Openmoko'),
       (nextval('technologies_id_seq'::regclass), 'OpenPOWER'),
       (nextval('technologies_id_seq'::regclass), 'OpenRasta'),
       (nextval('technologies_id_seq'::regclass), 'OpenRAVE'),
       (nextval('technologies_id_seq'::regclass), 'OpenROAD'),
       (nextval('technologies_id_seq'::regclass), 'OpenROV'),
       (nextval('technologies_id_seq'::regclass), 'OpenSPARC'),
       (nextval('technologies_id_seq'::regclass), 'OpenWGA'),
       (nextval('technologies_id_seq'::regclass), 'OpenXava'),
       (nextval('technologies_id_seq'::regclass), 'OPS5'),
       (nextval('technologies_id_seq'::regclass), 'OptimJ'),
       (nextval('technologies_id_seq'::regclass), 'Oracle Application Development Framework'),
       (nextval('technologies_id_seq'::regclass), 'Oracle Application Express'),
       (nextval('technologies_id_seq'::regclass), 'Oracle Forms'),
       (nextval('technologies_id_seq'::regclass), 'Oracle Reports'),
       (nextval('technologies_id_seq'::regclass), 'Orb swarm'),
       (nextval('technologies_id_seq'::regclass), 'Orc'),
       (nextval('technologies_id_seq'::regclass), 'Orchard Project'),
       (nextval('technologies_id_seq'::regclass), 'Oriel'),
       (nextval('technologies_id_seq'::regclass), 'Orion R28'),
       (nextval('technologies_id_seq'::regclass), 'Orwell'),
       (nextval('technologies_id_seq'::regclass), 'OutSystems'),
       (nextval('technologies_id_seq'::regclass), 'Ouya'),
       (nextval('technologies_id_seq'::regclass), 'P'),
       (nextval('technologies_id_seq'::regclass), 'P4'),
       (nextval('technologies_id_seq'::regclass), 'PACT I'),
       (nextval('technologies_id_seq'::regclass), 'Padrino'),
       (nextval('technologies_id_seq'::regclass), 'PALASM'),
       (nextval('technologies_id_seq'::regclass), 'Panda3D'),
       (nextval('technologies_id_seq'::regclass), 'PandaBoard'),
       (nextval('technologies_id_seq'::regclass), 'Pandesic'),
       (nextval('technologies_id_seq'::regclass), 'Pantheon'),
       (nextval('technologies_id_seq'::regclass), 'papaya CMS'),
       (nextval('technologies_id_seq'::regclass), 'Parallax P8X32A Propeller'),
       (nextval('technologies_id_seq'::regclass), 'Parallax Propeller'),
       (nextval('technologies_id_seq'::regclass), 'Parallella'),
       (nextval('technologies_id_seq'::regclass), 'ParaSail'),
       (nextval('technologies_id_seq'::regclass), 'PC532'),
       (nextval('technologies_id_seq'::regclass), 'PCASTL'),
       (nextval('technologies_id_seq'::regclass), 'PD'),
       (nextval('technologies_id_seq'::regclass), 'PEAR'),
       (nextval('technologies_id_seq'::regclass), 'Perl Data Language'),
       (nextval('technologies_id_seq'::regclass), 'Perl language structure'),
       (nextval('technologies_id_seq'::regclass), 'Ph7cms'),
       (nextval('technologies_id_seq'::regclass), 'Phalcon'),
       (nextval('technologies_id_seq'::regclass), 'Phire CMS'),
       (nextval('technologies_id_seq'::regclass), 'Phoenix'),
       (nextval('technologies_id_seq'::regclass), 'PHP Unit Testing Framework'),
       (nextval('technologies_id_seq'::regclass), 'PHP-Nuke'),
       (nextval('technologies_id_seq'::regclass), 'PhpCodeGenie'),
       (nextval('technologies_id_seq'::regclass), 'PHPRunner'),
       (nextval('technologies_id_seq'::regclass), 'PHPUnit'),
       (nextval('technologies_id_seq'::regclass), 'phpWebLog'),
       (nextval('technologies_id_seq'::regclass), 'phpWiki'),
       (nextval('technologies_id_seq'::regclass), 'Pick Basic'),
       (nextval('technologies_id_seq'::regclass), 'Picnic'),
       (nextval('technologies_id_seq'::regclass), 'Pico'),
       (nextval('technologies_id_seq'::regclass), 'Pict'),
       (nextval('technologies_id_seq'::regclass), 'Piet'),
       (nextval('technologies_id_seq'::regclass), 'PIKT'),
       (nextval('technologies_id_seq'::regclass), 'Pimcore'),
       (nextval('technologies_id_seq'::regclass), 'Pine64'),
       (nextval('technologies_id_seq'::regclass), 'PivotX'),
       (nextval('technologies_id_seq'::regclass), 'Pixie'),
       (nextval('technologies_id_seq'::regclass), 'PL/1'),
       (nextval('technologies_id_seq'::regclass), 'PL/C'),
       (nextval('technologies_id_seq'::regclass), 'PL/M'),
       (nextval('technologies_id_seq'::regclass), 'PLAICE'),
       (nextval('technologies_id_seq'::regclass), 'Play Framework'),
       (nextval('technologies_id_seq'::regclass), 'PlayStation Shader Language'),
       (nextval('technologies_id_seq'::regclass), 'Plone'),
       (nextval('technologies_id_seq'::regclass), 'Plus'),
       (nextval('technologies_id_seq'::regclass), 'PmWiki'),
       (nextval('technologies_id_seq'::regclass), 'PNMsoft'),
       (nextval('technologies_id_seq'::regclass), 'PocketSprite'),
       (nextval('technologies_id_seq'::regclass), 'POCO C++ Libraries'),
       (nextval('technologies_id_seq'::regclass), 'Polymorphic Programming Language'),
       (nextval('technologies_id_seq'::regclass), 'Pop PHP Framework'),
       (nextval('technologies_id_seq'::regclass), 'POP-11'),
       (nextval('technologies_id_seq'::regclass), 'POP-2'),
       (nextval('technologies_id_seq'::regclass), 'Poplog'),
       (nextval('technologies_id_seq'::regclass), 'POWER'),
       (nextval('technologies_id_seq'::regclass), 'Power Architecture'),
       (nextval('technologies_id_seq'::regclass), 'PowerBuilder'),
       (nextval('technologies_id_seq'::regclass), 'PowerPC'),
       (nextval('technologies_id_seq'::regclass), 'PRADO'),
       (nextval('technologies_id_seq'::regclass), 'Prestashop'),
       (nextval('technologies_id_seq'::regclass), 'ProcessWire'),
       (nextval('technologies_id_seq'::regclass), 'Prograph'),
       (nextval('technologies_id_seq'::regclass), 'Progress'),
       (nextval('technologies_id_seq'::regclass), 'Progress 4GL'),
       (nextval('technologies_id_seq'::regclass), 'PROIV'),
       (nextval('technologies_id_seq'::regclass), 'PROMAL'),
       (nextval('technologies_id_seq'::regclass), 'PROSE'),
       (nextval('technologies_id_seq'::regclass), 'PROSE modeling language'),
       (nextval('technologies_id_seq'::regclass), 'PS'),
       (nextval('technologies_id_seq'::regclass), 'Pure'),
       (nextval('technologies_id_seq'::regclass), 'PWCT'),
       (nextval('technologies_id_seq'::regclass), 'Pyjs'),
       (nextval('technologies_id_seq'::regclass), 'Pylons'),
       (nextval('technologies_id_seq'::regclass), 'Pylons Framework'),
       (nextval('technologies_id_seq'::regclass), 'Pyramid'),
       (nextval('technologies_id_seq'::regclass), 'Python Paste'),
       (nextval('technologies_id_seq'::regclass), 'P′′'),
       (nextval('technologies_id_seq'::regclass), 'QB64'),
       (nextval('technologies_id_seq'::regclass), 'Qcodo'),
       (nextval('technologies_id_seq'::regclass), 'QML'),
       (nextval('technologies_id_seq'::regclass), 'Qore'),
       (nextval('technologies_id_seq'::regclass), 'Qt Quick'),
       (nextval('technologies_id_seq'::regclass), 'Quartz Composer'),
       (nextval('technologies_id_seq'::regclass), 'QuickBASIC'),
       (nextval('technologies_id_seq'::regclass), 'Quixote'),
       (nextval('technologies_id_seq'::regclass), 'Radiant'),
       (nextval('technologies_id_seq'::regclass), 'Ramis'),
       (nextval('technologies_id_seq'::regclass), 'RAPID'),
       (nextval('technologies_id_seq'::regclass), 'RapidSMS'),
       (nextval('technologies_id_seq'::regclass), 'Rapira'),
       (nextval('technologies_id_seq'::regclass), 'Rascal'),
       (nextval('technologies_id_seq'::regclass), 'Ratfor'),
       (nextval('technologies_id_seq'::regclass), 'Rc'),
       (nextval('technologies_id_seq'::regclass), 'RDQL'),
       (nextval('technologies_id_seq'::regclass), 'React Fiber'),
       (nextval('technologies_id_seq'::regclass), 'React.js'),
       (nextval('technologies_id_seq'::regclass), 'READ/PRINT'),
       (nextval('technologies_id_seq'::regclass), 'Reaktor'),
       (nextval('technologies_id_seq'::regclass), 'REALbasic'),
       (nextval('technologies_id_seq'::regclass), 'REFAL'),
       (nextval('technologies_id_seq'::regclass), 'Refinery CMS'),
       (nextval('technologies_id_seq'::regclass), 'Regional Assembly Language'),
       (nextval('technologies_id_seq'::regclass), 'Remote Application Platform'),
       (nextval('technologies_id_seq'::regclass), 'RenderMan Shading Language'),
       (nextval('technologies_id_seq'::regclass), 'Responsive'),
       (nextval('technologies_id_seq'::regclass), 'Revolution'),
       (nextval('technologies_id_seq'::regclass), 'Rhomobile'),
       (nextval('technologies_id_seq'::regclass), 'RichFaces'),
       (nextval('technologies_id_seq'::regclass), 'RIFE'),
       (nextval('technologies_id_seq'::regclass), 'RobotCub'),
       (nextval('technologies_id_seq'::regclass), 'Rochester assembler'),
       (nextval('technologies_id_seq'::regclass), 'ROOP'),
       (nextval('technologies_id_seq'::regclass), 'RPG II'),
       (nextval('technologies_id_seq'::regclass), 'RPG III'),
       (nextval('technologies_id_seq'::regclass), 'RPG-II'),
       (nextval('technologies_id_seq'::regclass), 'RPG4'),
       (nextval('technologies_id_seq'::regclass), 'RPG400'),
       (nextval('technologies_id_seq'::regclass), 'RPGII'),
       (nextval('technologies_id_seq'::regclass), 'RPGIII'),
       (nextval('technologies_id_seq'::regclass), 'RPGIV'),
       (nextval('technologies_id_seq'::regclass), 'RPGLE'),
       (nextval('technologies_id_seq'::regclass), 'RPL'),
       (nextval('technologies_id_seq'::regclass), 'Ruby on Rails'),
       (nextval('technologies_id_seq'::regclass), 'Run BASIC'),
       (nextval('technologies_id_seq'::regclass), 'Rustlang'),
       (nextval('technologies_id_seq'::regclass), 'S-Lang'),
       (nextval('technologies_id_seq'::regclass), 'SAC'),
       (nextval('technologies_id_seq'::regclass), 'Sails.js'),
       (nextval('technologies_id_seq'::regclass), 'SALSA'),
       (nextval('technologies_id_seq'::regclass), 'SAM76'),
       (nextval('technologies_id_seq'::regclass), 'Sansa Framework'),
       (nextval('technologies_id_seq'::regclass), 'SAS language'),
       (nextval('technologies_id_seq'::regclass), 'SASL'),
       (nextval('technologies_id_seq'::regclass), 'SB+/SystemBuilder'),
       (nextval('technologies_id_seq'::regclass), 'Scalatra'),
       (nextval('technologies_id_seq'::regclass), 'Scilab'),
       (nextval('technologies_id_seq'::regclass), 'Self'),
       (nextval('technologies_id_seq'::regclass), 'Sellerdeck'),
       (nextval('technologies_id_seq'::regclass), 'Semantic MediaWiki Plus'),
       (nextval('technologies_id_seq'::regclass), 'Sencha Touch'),
       (nextval('technologies_id_seq'::regclass), 'Seneca'),
       (nextval('technologies_id_seq'::regclass), 'SequenceL'),
       (nextval('technologies_id_seq'::regclass), 'Sequentielle Formelübersetzung'),
       (nextval('technologies_id_seq'::regclass), 'Serendipity'),
       (nextval('technologies_id_seq'::regclass), 'ServiceNow'),
       (nextval('technologies_id_seq'::regclass), 'SETL'),
       (nextval('technologies_id_seq'::regclass), 'sh'),
       (nextval('technologies_id_seq'::regclass), 'Shakespeare'),
       (nextval('technologies_id_seq'::regclass), 'Shale Framework'),
       (nextval('technologies_id_seq'::regclass), 'SheerPower4GL'),
       (nextval('technologies_id_seq'::regclass), 'Short Code'),
       (nextval('technologies_id_seq'::regclass), 'SignalR'),
       (nextval('technologies_id_seq'::regclass), 'Silex'),
       (nextval('technologies_id_seq'::regclass), 'Silverlight‎'),
       (nextval('technologies_id_seq'::regclass), 'SilverStripe'),
       (nextval('technologies_id_seq'::regclass), 'Simputer'),
       (nextval('technologies_id_seq'::regclass), 'Sinatra'),
       (nextval('technologies_id_seq'::regclass), 'SISAL'),
       (nextval('technologies_id_seq'::regclass), 'SiteMesh'),
       (nextval('technologies_id_seq'::regclass), 'siva'),
       (nextval('technologies_id_seq'::regclass), 'SMALL'),
       (nextval('technologies_id_seq'::regclass), 'SMALL Machine Algol Like Language'),
       (nextval('technologies_id_seq'::regclass), 'Smalltalk-72'),
       (nextval('technologies_id_seq'::regclass), 'Smalltalk-76'),
       (nextval('technologies_id_seq'::regclass), 'Smart Framework PHP'),
       (nextval('technologies_id_seq'::regclass), 'SML'),
       (nextval('technologies_id_seq'::regclass), 'SMX'),
       (nextval('technologies_id_seq'::regclass), 'Snap'),
       (nextval('technologies_id_seq'::regclass), 'SNOBOL'),
       (nextval('technologies_id_seq'::regclass), 'Snowball'),
       (nextval('technologies_id_seq'::regclass), 'SolidRun'),
       (nextval('technologies_id_seq'::regclass), 'Solution stack'),
       (nextval('technologies_id_seq'::regclass), 'Sort Merge Generator'),
       (nextval('technologies_id_seq'::regclass), 'Space Programming Language'),
       (nextval('technologies_id_seq'::regclass), 'SparkFun Electronics'),
       (nextval('technologies_id_seq'::regclass), 'SPARQL'),
       (nextval('technologies_id_seq'::regclass), 'Speakeasy'),
       (nextval('technologies_id_seq'::regclass), 'Speedcoding'),
       (nextval('technologies_id_seq'::regclass), 'Spin'),
       (nextval('technologies_id_seq'::regclass), 'SPINE'),
       (nextval('technologies_id_seq'::regclass), 'SPIP'),
       (nextval('technologies_id_seq'::regclass), 'Spreadsheet'),
       (nextval('technologies_id_seq'::regclass), 'Spring Framework'),
       (nextval('technologies_id_seq'::regclass), 'Spring Roo'),
       (nextval('technologies_id_seq'::regclass), 'Spykee'),
       (nextval('technologies_id_seq'::regclass), 'SQL PL'),
       (nextval('technologies_id_seq'::regclass), 'SQL*Plus'),
       (nextval('technologies_id_seq'::regclass), 'SQLWindows'),
       (nextval('technologies_id_seq'::regclass), 'SR'),
       (nextval('technologies_id_seq'::regclass), 'SSJS'),
       (nextval('technologies_id_seq'::regclass), 'Standard Template Library'),
       (nextval('technologies_id_seq'::regclass), 'Stanislaus'),
       (nextval('technologies_id_seq'::regclass), 'STOS BASIC'),
       (nextval('technologies_id_seq'::regclass), 'Strawberry Prolog'),
       (nextval('technologies_id_seq'::regclass), 'StreamBase StreamSQL EventFlow'),
       (nextval('technologies_id_seq'::regclass), 'Stripes'),
       (nextval('technologies_id_seq'::regclass), 'Subtext'),
       (nextval('technologies_id_seq'::regclass), 'Sue'),
       (nextval('technologies_id_seq'::regclass), 'Sun Web Developer Pack'),
       (nextval('technologies_id_seq'::regclass), 'Super Micro Computer, Inc.'),
       (nextval('technologies_id_seq '::regclass), 'Superplan'),
       (nextval('technologies_id_seq '::regclass), 'SuperTalk'),
       (nextval('technologies_id_seq '::regclass), 'Suska'),
       (nextval('technologies_id_seq '::regclass), 'SwellRT'),
       (nextval('technologies_id_seq '::regclass), 'Synergy/DE'),
       (nextval('technologies_id_seq '::regclass), 'Synon'),
       (nextval('technologies_id_seq '::regclass), 'SystemC'),
       (nextval('technologies_id_seq '::regclass), 'SystemVerilog'),
       (nextval('technologies_id_seq '::regclass), 'T- SQL'),
       (nextval('technologies_id_seq '::regclass), 'Tacit'),
       (nextval('technologies_id_seq '::regclass), 'TACTIC'),
       (nextval('technologies_id_seq '::regclass), 'TADS'),
       (nextval('technologies_id_seq '::regclass), 'Tcl/Tk'),
       (nextval('technologies_id_seq '::regclass), 'Tea'),
       (nextval('technologies_id_seq '::regclass), 'TELCOMP'),
       (nextval('technologies_id_seq '::regclass), 'Tersus'),
       (nextval('technologies_id_seq '::regclass), 'Textpattern'),
       (nextval('technologies_id_seq '::regclass), 'The Bus Pirate'),
       (nextval('technologies_id_seq '::regclass), 'Thymio'),
       (nextval('technologies_id_seq '::regclass), 'TiddlyWiki'),
       (nextval('technologies_id_seq '::regclass), 'Tiki Wiki CMS Groupware'),
       (nextval('technologies_id_seq '::regclass), 'Tinkerforge'),
       (nextval('technologies_id_seq '::regclass), 'Tntnet'),
       (nextval('technologies_id_seq '::regclass), 'ToonTalk'),
       (nextval('technologies_id_seq '::regclass), 'Topincs'),
       (nextval('technologies_id_seq '::regclass), 'Tornado'),
       (nextval('technologies_id_seq '::regclass), 'TorqueScript'),
       (nextval('technologies_id_seq '::regclass), 'TRAC'),
       (nextval('technologies_id_seq '::regclass), 'Transcript'),
       (nextval('technologies_id_seq '::regclass), 'TREEMETA'),
       (nextval('technologies_id_seq '::regclass), 'Tronsmart'),
       (nextval('technologies_id_seq '::regclass), 'True BASIC'),
       (nextval('technologies_id_seq '::regclass), 'TS'),
       (nextval('technologies_id_seq '::regclass), 'TSQL'),
       (nextval('technologies_id_seq '::regclass), 'TTM'),
       (nextval('technologies_id_seq '::regclass), 'Tuk Tuk'),
       (nextval('technologies_id_seq '::regclass), 'Turbo Assembler'),
       (nextval('technologies_id_seq '::regclass), 'Turbo Basic'),
       (nextval('technologies_id_seq '::regclass), 'Turbo Pascal'),
       (nextval('technologies_id_seq '::regclass), 'TurboGears'),
       (nextval('technologies_id_seq '::regclass), 'Turing'),
       (nextval('technologies_id_seq '::regclass), 'Turris Omnia'),
       (nextval('technologies_id_seq '::regclass), 'TUTOR'),
       (nextval('technologies_id_seq '::regclass), 'Tutorial D'),
       (nextval('technologies_id_seq '::regclass), 'TWiki'),
       (nextval('technologies_id_seq '::regclass), 'TwistPHP'),
       (nextval('technologies_id_seq '::regclass), 'Typo'),
       (nextval('technologies_id_seq '::regclass), 'TYPO3'),
       (nextval('technologies_id_seq '::regclass), 'TYPO3 Flow'),
       (nextval('technologies_id_seq '::regclass), 'Ubercode'),
       (nextval('technologies_id_seq '::regclass), 'UDOO'),
       (nextval('technologies_id_seq '::regclass), 'Umbraco'),
       (nextval('technologies_id_seq '::regclass), 'Uniface'),
       (nextval('technologies_id_seq '::regclass), 'Unified Parallel C'),
       (nextval('technologies_id_seq '::regclass), 'Unify VISION'),
       (nextval('technologies_id_seq '::regclass), 'Unix shell'),
       (nextval('technologies_id_seq '::regclass), 'UnrealScript'),
       (nextval('technologies_id_seq '::regclass), 'Unsemantic'),
       (nextval('technologies_id_seq '::regclass), 'Urbiscript'),
       (nextval('technologies_id_seq '::regclass), 'Utilite'),
       (nextval('technologies_id_seq '::regclass), 'Utilite2'),
       (nextval('technologies_id_seq '::regclass), 'Vaadin'),
       (nextval('technologies_id_seq '::regclass), 'Vala'),
       (nextval('technologies_id_seq '::regclass), 'Vapor'),
       (nextval('technologies_id_seq '::regclass), 'VB'),
       (nextval('technologies_id_seq '::regclass), 'VB6'),
       (nextval('technologies_id_seq '::regclass), 'VEE'),
       (nextval('technologies_id_seq '::regclass), 'Verilog-AMS'),
       (nextval('technologies_id_seq '::regclass), 'VersaLogic'),
       (nextval('technologies_id_seq '::regclass), 'VFP'),
       (nextval('technologies_id_seq '::regclass), 'VHDL-AMS'),
       (nextval('technologies_id_seq '::regclass), 'VIA APC'),
       (nextval('technologies_id_seq '::regclass), 'VIA OpenBook'),
       (nextval('technologies_id_seq '::regclass), 'VIA Technologies'),
       (nextval('technologies_id_seq '::regclass), 'vibe.d'),
       (nextval('technologies_id_seq '::regclass), 'Vim script'),
       (nextval('technologies_id_seq '::regclass), 'Vimscript'),
       (nextval('technologies_id_seq '::regclass), 'VisiCalc'),
       (nextval('technologies_id_seq '::regclass), 'VisSim'),
       (nextval('technologies_id_seq '::regclass), 'Visual Basic.NET'),
       (nextval('technologies_id_seq '::regclass), 'Visual DataFlex'),
       (nextval('technologies_id_seq '::regclass), 'Visual FoxPro'),
       (nextval('technologies_id_seq '::regclass), 'Visual Prolog'),
       (nextval('technologies_id_seq '::regclass), 'VisualWorks'),
       (nextval('technologies_id_seq '::regclass), 'ViziApps'),
       (nextval('technologies_id_seq '::regclass), 'VRaptor'),
       (nextval('technologies_id_seq '::regclass), 'Wakanda'),
       (nextval('technologies_id_seq '::regclass), 'Wandboard'),
       (nextval('technologies_id_seq '::regclass), 'wasm'),
       (nextval('technologies_id_seq '::regclass), 'WaveMaker'),
       (nextval('technologies_id_seq '::regclass), 'web2py'),
       (nextval('technologies_id_seq '::regclass), 'WebGUI'),
       (nextval('technologies_id_seq '::regclass), 'WebMethods Flow'),
       (nextval('technologies_id_seq '::regclass), 'WebObjects'),
       (nextval('technologies_id_seq '::regclass), 'WebSphere sMash'),
       (nextval('technologies_id_seq '::regclass), 'Webware for Python'),
       (nextval('technologies_id_seq '::regclass), 'WebWork'),
       (nextval('technologies_id_seq '::regclass), 'Western Design Center'),
       (nextval('technologies_id_seq '::regclass), 'Whiley'),
       (nextval('technologies_id_seq '::regclass), 'Whirlwind assembler'),
       (nextval('technologies_id_seq '::regclass), 'Wiki.js'),
       (nextval('technologies_id_seq '::regclass), 'Winbatch'),
       (nextval('technologies_id_seq '::regclass), 'Windows batch language'),
       (nextval('technologies_id_seq '::regclass), 'Windows PowerShell'),
       (nextval('technologies_id_seq '::regclass), 'WinSystems, Inc'),
       (nextval('technologies_id_seq'::regclass), 'Wolfram Language'),
       (nextval('technologies_id_seq'::regclass), 'Wt'),
       (nextval('technologies_id_seq'::regclass), 'X++'),
       (nextval('technologies_id_seq'::regclass), 'x86'),
       (nextval('technologies_id_seq'::regclass), 'x86-64'),
       (nextval('technologies_id_seq'::regclass), 'XAML'),
       (nextval('technologies_id_seq'::regclass), 'Xaraya'),
       (nextval('technologies_id_seq'::regclass), 'XHP'),
       (nextval('technologies_id_seq'::regclass), 'XL'),
       (nextval('technologies_id_seq'::regclass), 'XOD'),
       (nextval('technologies_id_seq'::regclass), 'XOOPS'),
       (nextval('technologies_id_seq'::regclass), 'XOTcl'),
       (nextval('technologies_id_seq'::regclass), 'XPath'),
       (nextval('technologies_id_seq'::regclass), 'XProc'),
       (nextval('technologies_id_seq'::regclass), 'XSL Transformations'),
       (nextval('technologies_id_seq'::regclass), 'XUL'),
       (nextval('technologies_id_seq'::regclass), 'XWiki'),
       (nextval('technologies_id_seq'::regclass), 'Yellow'),
       (nextval('technologies_id_seq'::regclass), 'Yesod'),
       (nextval('technologies_id_seq'::regclass), 'Yii'),
       (nextval('technologies_id_seq'::regclass), 'Zend Framework'),
       (nextval('technologies_id_seq'::regclass), 'Zet'),
       (nextval('technologies_id_seq'::regclass), 'Zilog Z80'),
       (nextval('technologies_id_seq'::regclass), 'ZK'),
       (nextval('technologies_id_seq'::regclass), 'Zope'),
       (nextval('technologies_id_seq'::regclass), 'Zope 2'),
       (nextval('technologies_id_seq'::regclass), 'ZPL'),
       (nextval('technologies_id_seq'::regclass), 'ZPU'),
       (nextval('technologies_id_seq'::regclass), 'zsh'),
       (nextval('technologies_id_seq'::regclass), 'ztemplates'),
       (nextval('technologies_id_seq'::regclass), 'λProlog')